// Code generated by forge-dev. DO NOT EDIT.
// Source: spec.openapi.yaml
// SourceChecksum: sha256:4caf6b172e5d8d4132a25a8351884221270fd465dbe82a3122db5b665ef5ae10

package main

import (
	"context"
	"fmt"

	"github.com/alexandremahdhaoui/forge/pkg/mcpserver"
	"github.com/alexandremahdhaoui/forge/pkg/mcptypes"
	"github.com/alexandremahdhaoui/forge/pkg/mcputil"
	"github.com/modelcontextprotocol/go-sdk/mcp"
)

// LanguageFunc is the handler signature for the language tool.
// Report which language this engine speaks.
type LanguageFunc func(
	ctx context.Context,
	input RenderInput,
) (*LanguageOutput, error)

// RenderFunc is the handler signature for the render tool.
// Render every python manifest the workspace needs.
type RenderFunc func(
	ctx context.Context,
	input RenderInput,
) (*RenderOutput, error)

// DescribeFunc is the handler signature for the describe tool.
// Describe the runtime this language's members exec - artifacts, layout, env, prerequisites. Pure data.
type DescribeFunc func(
	ctx context.Context,
	input DescribeInput,
) (*RuntimeDescription, error)

// Handlers holds one implementation per tool declared in forge-dev.yaml.
// Every field is required. A nil field makes SetupMCPServer return an error
// rather than registering a tool that panics when called.
type Handlers struct {
	// Language implements the language tool.
	Language LanguageFunc
	// Render implements the render tool.
	Render RenderFunc
	// Describe implements the describe tool.
	Describe DescribeFunc
}

// SetupMCPServer creates the MCP server and registers every declared tool plus
// config-validate.
func SetupMCPServer(name string, version string, handlers Handlers) (*mcpserver.Server, error) {
	server := mcpserver.New(name, version)

	if handlers.Language == nil {
		return nil, fmt.Errorf("Handlers.Language is required for the %q tool", "language")
	}

	mcpserver.RegisterTool(server, &mcp.Tool{
		Name:        "language",
		Description: "Report which language this engine speaks.",
	}, wrapLanguage(handlers.Language))

	if handlers.Render == nil {
		return nil, fmt.Errorf("Handlers.Render is required for the %q tool", "render")
	}

	mcpserver.RegisterTool(server, &mcp.Tool{
		Name:        "render",
		Description: "Render every python manifest the workspace needs.",
	}, wrapRender(handlers.Render))

	if handlers.Describe == nil {
		return nil, fmt.Errorf("Handlers.Describe is required for the %q tool", "describe")
	}

	mcpserver.RegisterTool(server, &mcp.Tool{
		Name:        "describe",
		Description: "Describe the runtime this language's members exec - artifacts, layout, env, prerequisites. Pure data.",
	}, wrapDescribe(handlers.Describe))

	mcpserver.RegisterTool(server, &mcp.Tool{
		Name:        "config-validate",
		Description: fmt.Sprintf("Validate %s engine-specific spec configuration.", name),
	}, handleConfigValidate)

	return server, nil
}

// wrapLanguage adapts LanguageFunc to the MCP tool handler shape.
func wrapLanguage(fn LanguageFunc) func(
	context.Context, *mcp.CallToolRequest, RenderInput,
) (*mcp.CallToolResult, any, error) {
	return func(
		ctx context.Context,
		_ *mcp.CallToolRequest,
		input RenderInput,
	) (*mcp.CallToolResult, any, error) {
		output, err := fn(ctx, input)
		if err != nil {
			return nil, nil, err
		}

		return nil, output, nil
	}
}

// wrapRender adapts RenderFunc to the MCP tool handler shape.
func wrapRender(fn RenderFunc) func(
	context.Context, *mcp.CallToolRequest, RenderInput,
) (*mcp.CallToolResult, any, error) {
	return func(
		ctx context.Context,
		_ *mcp.CallToolRequest,
		input RenderInput,
	) (*mcp.CallToolResult, any, error) {
		output, err := fn(ctx, input)
		if err != nil {
			return nil, nil, err
		}

		return nil, output, nil
	}
}

// wrapDescribe adapts DescribeFunc to the MCP tool handler shape.
func wrapDescribe(fn DescribeFunc) func(
	context.Context, *mcp.CallToolRequest, DescribeInput,
) (*mcp.CallToolResult, any, error) {
	return func(
		ctx context.Context,
		_ *mcp.CallToolRequest,
		input DescribeInput,
	) (*mcp.CallToolResult, any, error) {
		output, err := fn(ctx, input)
		if err != nil {
			return nil, nil, err
		}

		return nil, output, nil
	}
}

// handleConfigValidate handles the config-validate MCP tool.
func handleConfigValidate(
	_ context.Context,
	_ *mcp.CallToolRequest,
	input mcptypes.ConfigValidateInput,
) (*mcp.CallToolResult, any, error) {
	output := ValidateMap(input.Spec)

	if output.Valid {
		result, artifact := mcputil.SuccessResultWithArtifact("Configuration is valid", output)

		return result, artifact, nil
	}

	result, artifact := mcputil.SuccessResultWithArtifact(
		fmt.Sprintf("Configuration validation failed with %d error(s)", len(output.Errors)),
		output,
	)

	return result, artifact, nil
}
