// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package clidrivermock

import (
	"context"

	"github.com/alexandremahdhaoui/forge-factory/internal/controller/statuscontroller"
	"github.com/alexandremahdhaoui/forge-factory/pkg/config"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStater creates a new instance of MockStater. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStater(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStater {
	mock := &MockStater{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStater is an autogenerated mock type for the Stater type
type MockStater struct {
	mock.Mock
}

type MockStater_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStater) EXPECT() *MockStater_Expecter {
	return &MockStater_Expecter{mock: &_m.Mock}
}

// Status provides a mock function for the type MockStater
func (_mock *MockStater) Status(context1 context.Context, factory config.Factory, s string) (statuscontroller.Report, error) {
	ret := _mock.Called(context1, factory, s)

	if len(ret) == 0 {
		panic("no return value specified for Status")
	}

	var r0 statuscontroller.Report
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, config.Factory, string) (statuscontroller.Report, error)); ok {
		return returnFunc(context1, factory, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, config.Factory, string) statuscontroller.Report); ok {
		r0 = returnFunc(context1, factory, s)
	} else {
		r0 = ret.Get(0).(statuscontroller.Report)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, config.Factory, string) error); ok {
		r1 = returnFunc(context1, factory, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStater_Status_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Status'
type MockStater_Status_Call struct {
	*mock.Call
}

// Status is a helper method to define mock.On call
//   - context1 context.Context
//   - factory config.Factory
//   - s string
func (_e *MockStater_Expecter) Status(context1 any, factory any, s any) *MockStater_Status_Call {
	return &MockStater_Status_Call{Call: _e.mock.On("Status", context1, factory, s)}
}

func (_c *MockStater_Status_Call) Run(run func(context1 context.Context, factory config.Factory, s string)) *MockStater_Status_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 config.Factory
		if args[1] != nil {
			arg1 = args[1].(config.Factory)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStater_Status_Call) Return(report statuscontroller.Report, err error) *MockStater_Status_Call {
	_c.Call.Return(report, err)
	return _c
}

func (_c *MockStater_Status_Call) RunAndReturn(run func(context1 context.Context, factory config.Factory, s string) (statuscontroller.Report, error)) *MockStater_Status_Call {
	_c.Call.Return(run)
	return _c
}
