package docscontroller

import (
	"fmt"
	"strings"

	"github.com/alexandremahdhaoui/forge-factory/internal/types/docstypes"
)

const Header = "<!-- Code generated by docgen. DO NOT EDIT. -->"

// RenderConcepts writes the reference a reader reaches for first. It comes from
// a yaml file so nobody edits prose that a schema already states.
func RenderConcepts(c docstypes.Concepts) (docstypes.File, error) {
	if strings.TrimSpace(c.Tool) == "" {
		return docstypes.File{}, fmt.Errorf("rendering concepts: tool is required")
	}

	var b strings.Builder

	fmt.Fprintf(&b, "%s\n\n# %s\n\n%s\n", Header, c.Tool, c.Summary)

	if len(c.Verbs) > 0 {
		b.WriteString("\n## Verbs\n\n| Verb | Does |\n|---|---|\n")

		for _, v := range c.Verbs {
			name := v.Name

			if v.Args != "" {
				name += " " + v.Args
			}

			fmt.Fprintf(&b, "| `%s` | %s |\n", name, v.Summary)
		}
	}

	if len(c.Concepts) > 0 {
		b.WriteString("\n## Concepts\n")

		for _, concept := range c.Concepts {
			fmt.Fprintf(&b, "\n### %s\n\n%s\n", concept.Name, concept.Summary)

			if concept.Detail != "" {
				fmt.Fprintf(&b, "\n%s\n", concept.Detail)
			}

			if len(concept.SeeAlso) > 0 {
				fmt.Fprintf(&b, "\nSee also: %s\n", strings.Join(concept.SeeAlso, ", "))
			}
		}
	}

	return docstypes.File{Path: "docs/concepts.md", Content: b.String()}, nil
}

// RenderDecisions writes the closed questions, so nobody reopens one.
func RenderDecisions(d docstypes.Decisions) (docstypes.File, error) {
	var b strings.Builder

	fmt.Fprintf(&b, "%s\n\n# Decisions\n\nClosed questions. Each names the date it closed.\n", Header)

	for _, decision := range d.Decisions {
		if strings.TrimSpace(decision.Title) == "" {
			return docstypes.File{}, fmt.Errorf("rendering decisions: every decision needs a title")
		}

		fmt.Fprintf(&b, "\n## %s\n\n%s\n\n**Decided %s.** %s\n",
			decision.Title, decision.Decision, decision.Date, decision.Because)
	}

	return docstypes.File{Path: "docs/decisions.md", Content: b.String()}, nil
}
