all: false
template: testify
template-data:
  unroll-variadic: true
filename: "zz_generated.{{.InterfaceName}}.go"
formatter: goimports

packages:
  github.com/alexandremahdhaoui/forge-factory/internal/adapter/gitadapter:
    config:
      dir: internal/mocks/gitadaptermock
      pkgname: gitadaptermock
    interfaces:
      Git:

  github.com/alexandremahdhaoui/forge-factory/internal/adapter/execadapter:
    config:
      dir: internal/mocks/execadaptermock
      pkgname: execadaptermock
    interfaces:
      Runner:

  github.com/alexandremahdhaoui/forge-factory/internal/adapter/engineadapter:
    config:
      dir: internal/mocks/engineadaptermock
      pkgname: engineadaptermock
    interfaces:
      Caller:

  github.com/alexandremahdhaoui/forge-factory/internal/adapter/fsadapter:
    config:
      dir: internal/mocks/fsadaptermock
      pkgname: fsadaptermock
    interfaces:
      FS:

  github.com/alexandremahdhaoui/forge-factory/internal/adapter/repoadapter:
    config:
      dir: internal/mocks/repoadaptermock
      pkgname: repoadaptermock
    interfaces:
      Reader:

  github.com/alexandremahdhaoui/forge-factory/internal/controller/clonecontroller:
    config:
      dir: internal/mocks/clonecontrollermock
      pkgname: clonecontrollermock
    interfaces:
      Cloner:

  github.com/alexandremahdhaoui/forge-factory/internal/controller/synccontroller:
    config:
      dir: internal/mocks/synccontrollermock
      pkgname: synccontrollermock
    interfaces:
      Syncer:

  github.com/alexandremahdhaoui/forge-factory/internal/controller/revisioncontroller:
    config:
      dir: internal/mocks/revisioncontrollermock
      pkgname: revisioncontrollermock
    interfaces:
      Reviser:

  github.com/alexandremahdhaoui/forge-factory/internal/controller/statuscontroller:
    config:
      dir: internal/mocks/statuscontrollermock
      pkgname: statuscontrollermock
    interfaces:
      Stater:
