// Code generated by forge-dev. DO NOT EDIT.
// Source: forge-dev.yaml + spec.openapi.yaml
// SourceChecksum: sha256:13cbb16a64d4a757f49f28890da0972c9f81bacc87d64107314bdc27d8216e7a

package main

import (
	"context"
	"fmt"

	"github.com/alexandremahdhaoui/forge/pkg/enginecli"
)

// Name is the engine name.
const Name = "factory-lang-typescript"

// Version information (set via ldflags during build).
// Default is "dev" so GetEffectiveVersion() reads actual version from Go's debug.ReadBuildInfo()
// when running via "go run module@version".
var (
	Version        = "dev"
	CommitSHA      = "unknown"
	BuildTimestamp = "unknown"
)

// main is the entry point for the factory-lang-typescript engine.
func main() {
	enginecli.Bootstrap(enginecli.Config{
		Name:           Name,
		Version:        Version,
		CommitSHA:      CommitSHA,
		BuildTimestamp: BuildTimestamp,
		RunCLI:         nil, // Generated engines are MCP-only
		RunMCP:         runMCPServer,
		DocsConfig:     docsConfig,
	})
}

// runMCPServer creates and runs the MCP server.
func runMCPServer() error {
	server, err := SetupMCPServer(Name, Version, NewHandlers())
	if err != nil {
		return fmt.Errorf("setting up MCP server: %w", err)
	}

	// Register docs MCP tools (docs-list, docs-get)
	if err := RegisterDocsMCPTools(server); err != nil {
		return fmt.Errorf("registering docs MCP tools: %w", err)
	}

	if err := server.Run(context.Background()); err != nil {
		return fmt.Errorf("running MCP server: %w", err)
	}

	return nil
}

// NewHandlers must be implemented by the engine author in a separate file.
// It returns one implementation per tool declared in forge-dev.yaml:
//
//	func NewHandlers() Handlers {
//		return Handlers{
//			Language: func(ctx context.Context, input RenderInput) (*LanguageOutput, error) {
//				panic("language is not implemented")
//			},
//			Render: func(ctx context.Context, input RenderInput) (*RenderOutput, error) {
//				panic("render is not implemented")
//			},
//		}
//	}
