// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repoadaptermock

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockReader creates a new instance of MockReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReader {
	mock := &MockReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockReader is an autogenerated mock type for the Reader type
type MockReader struct {
	mock.Mock
}

type MockReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReader) EXPECT() *MockReader_Expecter {
	return &MockReader_Expecter{mock: &_m.Mock}
}

// Identity provides a mock function for the type MockReader
func (_mock *MockReader) Identity(repoPath string) (map[string]string, error) {
	ret := _mock.Called(repoPath)

	if len(ret) == 0 {
		panic("no return value specified for Identity")
	}

	var r0 map[string]string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (map[string]string, error)); ok {
		return returnFunc(repoPath)
	}
	if returnFunc, ok := ret.Get(0).(func(string) map[string]string); ok {
		r0 = returnFunc(repoPath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(repoPath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReader_Identity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Identity'
type MockReader_Identity_Call struct {
	*mock.Call
}

// Identity is a helper method to define mock.On call
//   - repoPath string
func (_e *MockReader_Expecter) Identity(repoPath any) *MockReader_Identity_Call {
	return &MockReader_Identity_Call{Call: _e.mock.On("Identity", repoPath)}
}

func (_c *MockReader_Identity_Call) Run(run func(repoPath string)) *MockReader_Identity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReader_Identity_Call) Return(stringToString map[string]string, err error) *MockReader_Identity_Call {
	_c.Call.Return(stringToString, err)
	return _c
}

func (_c *MockReader_Identity_Call) RunAndReturn(run func(repoPath string) (map[string]string, error)) *MockReader_Identity_Call {
	_c.Call.Return(run)
	return _c
}
