// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package clonecontrollermock

import (
	"context"

	"github.com/alexandremahdhaoui/forge-factory/internal/controller/clonecontroller"
	"github.com/alexandremahdhaoui/forge-factory/pkg/config"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCloner creates a new instance of MockCloner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCloner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCloner {
	mock := &MockCloner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCloner is an autogenerated mock type for the Cloner type
type MockCloner struct {
	mock.Mock
}

type MockCloner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCloner) EXPECT() *MockCloner_Expecter {
	return &MockCloner_Expecter{mock: &_m.Mock}
}

// Clone provides a mock function for the type MockCloner
func (_mock *MockCloner) Clone(ctx context.Context, f config.Factory, root string) (clonecontroller.Report, error) {
	ret := _mock.Called(ctx, f, root)

	if len(ret) == 0 {
		panic("no return value specified for Clone")
	}

	var r0 clonecontroller.Report
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, config.Factory, string) (clonecontroller.Report, error)); ok {
		return returnFunc(ctx, f, root)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, config.Factory, string) clonecontroller.Report); ok {
		r0 = returnFunc(ctx, f, root)
	} else {
		r0 = ret.Get(0).(clonecontroller.Report)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, config.Factory, string) error); ok {
		r1 = returnFunc(ctx, f, root)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCloner_Clone_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Clone'
type MockCloner_Clone_Call struct {
	*mock.Call
}

// Clone is a helper method to define mock.On call
//   - ctx context.Context
//   - f config.Factory
//   - root string
func (_e *MockCloner_Expecter) Clone(ctx any, f any, root any) *MockCloner_Clone_Call {
	return &MockCloner_Clone_Call{Call: _e.mock.On("Clone", ctx, f, root)}
}

func (_c *MockCloner_Clone_Call) Run(run func(ctx context.Context, f config.Factory, root string)) *MockCloner_Clone_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 config.Factory
		if args[1] != nil {
			arg1 = args[1].(config.Factory)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCloner_Clone_Call) Return(report clonecontroller.Report, err error) *MockCloner_Clone_Call {
	_c.Call.Return(report, err)
	return _c
}

func (_c *MockCloner_Clone_Call) RunAndReturn(run func(ctx context.Context, f config.Factory, root string) (clonecontroller.Report, error)) *MockCloner_Clone_Call {
	_c.Call.Return(run)
	return _c
}
