#!/bin/sh
set -eu

go run ./cmd/docgen >/dev/null

if ! git diff --quiet -- docs/concepts.md docs/decisions.md 'cmd/*/docs'; then
    echo "generated docs are stale. run: go run ./cmd/docgen" >&2
    git --no-pager diff --stat -- docs/concepts.md docs/decisions.md 'cmd/*/docs' >&2
    exit 1
fi

fail=0

for f in docs/concepts.md docs/decisions.md; do
    if ! head -1 "$f" | grep -q "Code generated by docgen"; then
        echo "$f has no generated header, so nothing stops a human editing it" >&2
        fail=1
    fi
done

# usage.md comes from docgen, schema.md and list.yaml from forge-dev. Two
# generators, and neither writes what the other owns. forge-dev marks list.yaml
# and not schema.md, so schema.md is held current by the diff check above.
for f in cmd/factory-lang-*/docs/usage.md cmd/factory-lang-*/docs/list.yaml; do
    if ! grep -q "Code generated" "$f"; then
        echo "$f is not marked generated, so nothing stops a human editing it" >&2
        fail=1
    fi
done

for f in README.md; do
    if head -1 "$f" | grep -q "Code generated"; then
        echo "$f claims to be generated but it is the hand written guide" >&2
        fail=1
    fi
done

if [ "$fail" -eq 0 ]; then
    echo "generated docs are current, and only the README is hand written"
fi

exit "$fail"
