// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package gitadaptermock

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockGit creates a new instance of MockGit. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGit(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGit {
	mock := &MockGit{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGit is an autogenerated mock type for the Git type
type MockGit struct {
	mock.Mock
}

type MockGit_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGit) EXPECT() *MockGit_Expecter {
	return &MockGit_Expecter{mock: &_m.Mock}
}

// Add provides a mock function for the type MockGit
func (_mock *MockGit) Add(ctx context.Context, dir string, path string) error {
	ret := _mock.Called(ctx, dir, path)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, dir, path)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGit_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockGit_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx context.Context
//   - dir string
//   - path string
func (_e *MockGit_Expecter) Add(ctx any, dir any, path any) *MockGit_Add_Call {
	return &MockGit_Add_Call{Call: _e.mock.On("Add", ctx, dir, path)}
}

func (_c *MockGit_Add_Call) Run(run func(ctx context.Context, dir string, path string)) *MockGit_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGit_Add_Call) Return(err error) *MockGit_Add_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGit_Add_Call) RunAndReturn(run func(ctx context.Context, dir string, path string) error) *MockGit_Add_Call {
	_c.Call.Return(run)
	return _c
}

// AheadBehind provides a mock function for the type MockGit
func (_mock *MockGit) AheadBehind(ctx context.Context, dir string, ref string) (int, int, error) {
	ret := _mock.Called(ctx, dir, ref)

	if len(ret) == 0 {
		panic("no return value specified for AheadBehind")
	}

	var r0 int
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (int, int, error)); ok {
		return returnFunc(ctx, dir, ref)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) int); ok {
		r0 = returnFunc(ctx, dir, ref)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) int); ok {
		r1 = returnFunc(ctx, dir, ref)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = returnFunc(ctx, dir, ref)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockGit_AheadBehind_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AheadBehind'
type MockGit_AheadBehind_Call struct {
	*mock.Call
}

// AheadBehind is a helper method to define mock.On call
//   - ctx context.Context
//   - dir string
//   - ref string
func (_e *MockGit_Expecter) AheadBehind(ctx any, dir any, ref any) *MockGit_AheadBehind_Call {
	return &MockGit_AheadBehind_Call{Call: _e.mock.On("AheadBehind", ctx, dir, ref)}
}

func (_c *MockGit_AheadBehind_Call) Run(run func(ctx context.Context, dir string, ref string)) *MockGit_AheadBehind_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGit_AheadBehind_Call) Return(n int, n1 int, err error) *MockGit_AheadBehind_Call {
	_c.Call.Return(n, n1, err)
	return _c
}

func (_c *MockGit_AheadBehind_Call) RunAndReturn(run func(ctx context.Context, dir string, ref string) (int, int, error)) *MockGit_AheadBehind_Call {
	_c.Call.Return(run)
	return _c
}

// Checkout provides a mock function for the type MockGit
func (_mock *MockGit) Checkout(ctx context.Context, dir string, sha string) error {
	ret := _mock.Called(ctx, dir, sha)

	if len(ret) == 0 {
		panic("no return value specified for Checkout")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, dir, sha)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGit_Checkout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Checkout'
type MockGit_Checkout_Call struct {
	*mock.Call
}

// Checkout is a helper method to define mock.On call
//   - ctx context.Context
//   - dir string
//   - sha string
func (_e *MockGit_Expecter) Checkout(ctx any, dir any, sha any) *MockGit_Checkout_Call {
	return &MockGit_Checkout_Call{Call: _e.mock.On("Checkout", ctx, dir, sha)}
}

func (_c *MockGit_Checkout_Call) Run(run func(ctx context.Context, dir string, sha string)) *MockGit_Checkout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGit_Checkout_Call) Return(err error) *MockGit_Checkout_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGit_Checkout_Call) RunAndReturn(run func(ctx context.Context, dir string, sha string) error) *MockGit_Checkout_Call {
	_c.Call.Return(run)
	return _c
}

// Clone provides a mock function for the type MockGit
func (_mock *MockGit) Clone(ctx context.Context, url string, dir string) error {
	ret := _mock.Called(ctx, url, dir)

	if len(ret) == 0 {
		panic("no return value specified for Clone")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, url, dir)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGit_Clone_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Clone'
type MockGit_Clone_Call struct {
	*mock.Call
}

// Clone is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - dir string
func (_e *MockGit_Expecter) Clone(ctx any, url any, dir any) *MockGit_Clone_Call {
	return &MockGit_Clone_Call{Call: _e.mock.On("Clone", ctx, url, dir)}
}

func (_c *MockGit_Clone_Call) Run(run func(ctx context.Context, url string, dir string)) *MockGit_Clone_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGit_Clone_Call) Return(err error) *MockGit_Clone_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGit_Clone_Call) RunAndReturn(run func(ctx context.Context, url string, dir string) error) *MockGit_Clone_Call {
	_c.Call.Return(run)
	return _c
}

// Commit provides a mock function for the type MockGit
func (_mock *MockGit) Commit(ctx context.Context, dir string, message string) error {
	ret := _mock.Called(ctx, dir, message)

	if len(ret) == 0 {
		panic("no return value specified for Commit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, dir, message)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGit_Commit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Commit'
type MockGit_Commit_Call struct {
	*mock.Call
}

// Commit is a helper method to define mock.On call
//   - ctx context.Context
//   - dir string
//   - message string
func (_e *MockGit_Expecter) Commit(ctx any, dir any, message any) *MockGit_Commit_Call {
	return &MockGit_Commit_Call{Call: _e.mock.On("Commit", ctx, dir, message)}
}

func (_c *MockGit_Commit_Call) Run(run func(ctx context.Context, dir string, message string)) *MockGit_Commit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGit_Commit_Call) Return(err error) *MockGit_Commit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGit_Commit_Call) RunAndReturn(run func(ctx context.Context, dir string, message string) error) *MockGit_Commit_Call {
	_c.Call.Return(run)
	return _c
}

// Dirty provides a mock function for the type MockGit
func (_mock *MockGit) Dirty(ctx context.Context, dir string) (bool, error) {
	ret := _mock.Called(ctx, dir)

	if len(ret) == 0 {
		panic("no return value specified for Dirty")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, dir)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, dir)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, dir)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGit_Dirty_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Dirty'
type MockGit_Dirty_Call struct {
	*mock.Call
}

// Dirty is a helper method to define mock.On call
//   - ctx context.Context
//   - dir string
func (_e *MockGit_Expecter) Dirty(ctx any, dir any) *MockGit_Dirty_Call {
	return &MockGit_Dirty_Call{Call: _e.mock.On("Dirty", ctx, dir)}
}

func (_c *MockGit_Dirty_Call) Run(run func(ctx context.Context, dir string)) *MockGit_Dirty_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGit_Dirty_Call) Return(b bool, err error) *MockGit_Dirty_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockGit_Dirty_Call) RunAndReturn(run func(ctx context.Context, dir string) (bool, error)) *MockGit_Dirty_Call {
	_c.Call.Return(run)
	return _c
}

// Fetch provides a mock function for the type MockGit
func (_mock *MockGit) Fetch(ctx context.Context, dir string) error {
	ret := _mock.Called(ctx, dir)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, dir)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGit_Fetch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fetch'
type MockGit_Fetch_Call struct {
	*mock.Call
}

// Fetch is a helper method to define mock.On call
//   - ctx context.Context
//   - dir string
func (_e *MockGit_Expecter) Fetch(ctx any, dir any) *MockGit_Fetch_Call {
	return &MockGit_Fetch_Call{Call: _e.mock.On("Fetch", ctx, dir)}
}

func (_c *MockGit_Fetch_Call) Run(run func(ctx context.Context, dir string)) *MockGit_Fetch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGit_Fetch_Call) Return(err error) *MockGit_Fetch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGit_Fetch_Call) RunAndReturn(run func(ctx context.Context, dir string) error) *MockGit_Fetch_Call {
	_c.Call.Return(run)
	return _c
}

// HeadSHA provides a mock function for the type MockGit
func (_mock *MockGit) HeadSHA(ctx context.Context, dir string) (string, error) {
	ret := _mock.Called(ctx, dir)

	if len(ret) == 0 {
		panic("no return value specified for HeadSHA")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, dir)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, dir)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, dir)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGit_HeadSHA_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HeadSHA'
type MockGit_HeadSHA_Call struct {
	*mock.Call
}

// HeadSHA is a helper method to define mock.On call
//   - ctx context.Context
//   - dir string
func (_e *MockGit_Expecter) HeadSHA(ctx any, dir any) *MockGit_HeadSHA_Call {
	return &MockGit_HeadSHA_Call{Call: _e.mock.On("HeadSHA", ctx, dir)}
}

func (_c *MockGit_HeadSHA_Call) Run(run func(ctx context.Context, dir string)) *MockGit_HeadSHA_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGit_HeadSHA_Call) Return(s string, err error) *MockGit_HeadSHA_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockGit_HeadSHA_Call) RunAndReturn(run func(ctx context.Context, dir string) (string, error)) *MockGit_HeadSHA_Call {
	_c.Call.Return(run)
	return _c
}

// Init provides a mock function for the type MockGit
func (_mock *MockGit) Init(ctx context.Context, dir string) error {
	ret := _mock.Called(ctx, dir)

	if len(ret) == 0 {
		panic("no return value specified for Init")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, dir)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGit_Init_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Init'
type MockGit_Init_Call struct {
	*mock.Call
}

// Init is a helper method to define mock.On call
//   - ctx context.Context
//   - dir string
func (_e *MockGit_Expecter) Init(ctx any, dir any) *MockGit_Init_Call {
	return &MockGit_Init_Call{Call: _e.mock.On("Init", ctx, dir)}
}

func (_c *MockGit_Init_Call) Run(run func(ctx context.Context, dir string)) *MockGit_Init_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGit_Init_Call) Return(err error) *MockGit_Init_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGit_Init_Call) RunAndReturn(run func(ctx context.Context, dir string) error) *MockGit_Init_Call {
	_c.Call.Return(run)
	return _c
}

// IsRepo provides a mock function for the type MockGit
func (_mock *MockGit) IsRepo(ctx context.Context, dir string) (bool, error) {
	ret := _mock.Called(ctx, dir)

	if len(ret) == 0 {
		panic("no return value specified for IsRepo")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, dir)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, dir)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, dir)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGit_IsRepo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsRepo'
type MockGit_IsRepo_Call struct {
	*mock.Call
}

// IsRepo is a helper method to define mock.On call
//   - ctx context.Context
//   - dir string
func (_e *MockGit_Expecter) IsRepo(ctx any, dir any) *MockGit_IsRepo_Call {
	return &MockGit_IsRepo_Call{Call: _e.mock.On("IsRepo", ctx, dir)}
}

func (_c *MockGit_IsRepo_Call) Run(run func(ctx context.Context, dir string)) *MockGit_IsRepo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGit_IsRepo_Call) Return(b bool, err error) *MockGit_IsRepo_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockGit_IsRepo_Call) RunAndReturn(run func(ctx context.Context, dir string) (bool, error)) *MockGit_IsRepo_Call {
	_c.Call.Return(run)
	return _c
}

// LatestTag provides a mock function for the type MockGit
func (_mock *MockGit) LatestTag(ctx context.Context, dir string) (string, error) {
	ret := _mock.Called(ctx, dir)

	if len(ret) == 0 {
		panic("no return value specified for LatestTag")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, dir)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, dir)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, dir)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGit_LatestTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LatestTag'
type MockGit_LatestTag_Call struct {
	*mock.Call
}

// LatestTag is a helper method to define mock.On call
//   - ctx context.Context
//   - dir string
func (_e *MockGit_Expecter) LatestTag(ctx any, dir any) *MockGit_LatestTag_Call {
	return &MockGit_LatestTag_Call{Call: _e.mock.On("LatestTag", ctx, dir)}
}

func (_c *MockGit_LatestTag_Call) Run(run func(ctx context.Context, dir string)) *MockGit_LatestTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGit_LatestTag_Call) Return(s string, err error) *MockGit_LatestTag_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockGit_LatestTag_Call) RunAndReturn(run func(ctx context.Context, dir string) (string, error)) *MockGit_LatestTag_Call {
	_c.Call.Return(run)
	return _c
}

// LsTree provides a mock function for the type MockGit
func (_mock *MockGit) LsTree(ctx context.Context, dir string, rev string, path string) ([]string, error) {
	ret := _mock.Called(ctx, dir, rev, path)

	if len(ret) == 0 {
		panic("no return value specified for LsTree")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) ([]string, error)); ok {
		return returnFunc(ctx, dir, rev, path)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) []string); ok {
		r0 = returnFunc(ctx, dir, rev, path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, dir, rev, path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGit_LsTree_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LsTree'
type MockGit_LsTree_Call struct {
	*mock.Call
}

// LsTree is a helper method to define mock.On call
//   - ctx context.Context
//   - dir string
//   - rev string
//   - path string
func (_e *MockGit_Expecter) LsTree(ctx any, dir any, rev any, path any) *MockGit_LsTree_Call {
	return &MockGit_LsTree_Call{Call: _e.mock.On("LsTree", ctx, dir, rev, path)}
}

func (_c *MockGit_LsTree_Call) Run(run func(ctx context.Context, dir string, rev string, path string)) *MockGit_LsTree_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockGit_LsTree_Call) Return(strings []string, err error) *MockGit_LsTree_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockGit_LsTree_Call) RunAndReturn(run func(ctx context.Context, dir string, rev string, path string) ([]string, error)) *MockGit_LsTree_Call {
	_c.Call.Return(run)
	return _c
}

// RemoteSHA provides a mock function for the type MockGit
func (_mock *MockGit) RemoteSHA(ctx context.Context, url string, ref string) (string, error) {
	ret := _mock.Called(ctx, url, ref)

	if len(ret) == 0 {
		panic("no return value specified for RemoteSHA")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return returnFunc(ctx, url, ref)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = returnFunc(ctx, url, ref)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, url, ref)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGit_RemoteSHA_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoteSHA'
type MockGit_RemoteSHA_Call struct {
	*mock.Call
}

// RemoteSHA is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - ref string
func (_e *MockGit_Expecter) RemoteSHA(ctx any, url any, ref any) *MockGit_RemoteSHA_Call {
	return &MockGit_RemoteSHA_Call{Call: _e.mock.On("RemoteSHA", ctx, url, ref)}
}

func (_c *MockGit_RemoteSHA_Call) Run(run func(ctx context.Context, url string, ref string)) *MockGit_RemoteSHA_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGit_RemoteSHA_Call) Return(s string, err error) *MockGit_RemoteSHA_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockGit_RemoteSHA_Call) RunAndReturn(run func(ctx context.Context, url string, ref string) (string, error)) *MockGit_RemoteSHA_Call {
	_c.Call.Return(run)
	return _c
}

// Show provides a mock function for the type MockGit
func (_mock *MockGit) Show(ctx context.Context, dir string, rev string, path string) (string, bool, error) {
	ret := _mock.Called(ctx, dir, rev, path)

	if len(ret) == 0 {
		panic("no return value specified for Show")
	}

	var r0 string
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (string, bool, error)); ok {
		return returnFunc(ctx, dir, rev, path)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) string); ok {
		r0 = returnFunc(ctx, dir, rev, path)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) bool); ok {
		r1 = returnFunc(ctx, dir, rev, path)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string, string) error); ok {
		r2 = returnFunc(ctx, dir, rev, path)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockGit_Show_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Show'
type MockGit_Show_Call struct {
	*mock.Call
}

// Show is a helper method to define mock.On call
//   - ctx context.Context
//   - dir string
//   - rev string
//   - path string
func (_e *MockGit_Expecter) Show(ctx any, dir any, rev any, path any) *MockGit_Show_Call {
	return &MockGit_Show_Call{Call: _e.mock.On("Show", ctx, dir, rev, path)}
}

func (_c *MockGit_Show_Call) Run(run func(ctx context.Context, dir string, rev string, path string)) *MockGit_Show_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockGit_Show_Call) Return(s string, b bool, err error) *MockGit_Show_Call {
	_c.Call.Return(s, b, err)
	return _c
}

func (_c *MockGit_Show_Call) RunAndReturn(run func(ctx context.Context, dir string, rev string, path string) (string, bool, error)) *MockGit_Show_Call {
	_c.Call.Return(run)
	return _c
}

// WorktreeHash provides a mock function for the type MockGit
func (_mock *MockGit) WorktreeHash(ctx context.Context, dir string) (string, error) {
	ret := _mock.Called(ctx, dir)

	if len(ret) == 0 {
		panic("no return value specified for WorktreeHash")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, dir)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, dir)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, dir)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGit_WorktreeHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WorktreeHash'
type MockGit_WorktreeHash_Call struct {
	*mock.Call
}

// WorktreeHash is a helper method to define mock.On call
//   - ctx context.Context
//   - dir string
func (_e *MockGit_Expecter) WorktreeHash(ctx any, dir any) *MockGit_WorktreeHash_Call {
	return &MockGit_WorktreeHash_Call{Call: _e.mock.On("WorktreeHash", ctx, dir)}
}

func (_c *MockGit_WorktreeHash_Call) Run(run func(ctx context.Context, dir string)) *MockGit_WorktreeHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGit_WorktreeHash_Call) Return(s string, err error) *MockGit_WorktreeHash_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockGit_WorktreeHash_Call) RunAndReturn(run func(ctx context.Context, dir string) (string, error)) *MockGit_WorktreeHash_Call {
	_c.Call.Return(run)
	return _c
}
