// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package revisioncontrollermock

import (
	"context"

	"github.com/alexandremahdhaoui/forge-factory/internal/controller/revisioncontroller"
	"github.com/alexandremahdhaoui/forge-factory/pkg/config"
	mock "github.com/stretchr/testify/mock"
)

// NewMockReviser creates a new instance of MockReviser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReviser(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReviser {
	mock := &MockReviser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockReviser is an autogenerated mock type for the Reviser type
type MockReviser struct {
	mock.Mock
}

type MockReviser_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReviser) EXPECT() *MockReviser_Expecter {
	return &MockReviser_Expecter{mock: &_m.Mock}
}

// Checkout provides a mock function for the type MockReviser
func (_mock *MockReviser) Checkout(ctx context.Context, f config.Factory, root string, id string) (revisioncontroller.Result, error) {
	ret := _mock.Called(ctx, f, root, id)

	if len(ret) == 0 {
		panic("no return value specified for Checkout")
	}

	var r0 revisioncontroller.Result
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, config.Factory, string, string) (revisioncontroller.Result, error)); ok {
		return returnFunc(ctx, f, root, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, config.Factory, string, string) revisioncontroller.Result); ok {
		r0 = returnFunc(ctx, f, root, id)
	} else {
		r0 = ret.Get(0).(revisioncontroller.Result)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, config.Factory, string, string) error); ok {
		r1 = returnFunc(ctx, f, root, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReviser_Checkout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Checkout'
type MockReviser_Checkout_Call struct {
	*mock.Call
}

// Checkout is a helper method to define mock.On call
//   - ctx context.Context
//   - f config.Factory
//   - root string
//   - id string
func (_e *MockReviser_Expecter) Checkout(ctx any, f any, root any, id any) *MockReviser_Checkout_Call {
	return &MockReviser_Checkout_Call{Call: _e.mock.On("Checkout", ctx, f, root, id)}
}

func (_c *MockReviser_Checkout_Call) Run(run func(ctx context.Context, f config.Factory, root string, id string)) *MockReviser_Checkout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 config.Factory
		if args[1] != nil {
			arg1 = args[1].(config.Factory)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockReviser_Checkout_Call) Return(result revisioncontroller.Result, err error) *MockReviser_Checkout_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *MockReviser_Checkout_Call) RunAndReturn(run func(ctx context.Context, f config.Factory, root string, id string) (revisioncontroller.Result, error)) *MockReviser_Checkout_Call {
	_c.Call.Return(run)
	return _c
}
