// Code generated by forge-dev. DO NOT EDIT.
// Source: spec.openapi.yaml
// SourceChecksum: sha256:7b2d408d327463004e97504957bfef0d44ac9f3d6eb7f8512b3d9e17a1fc5181

package main

import (
	"context"
	"fmt"

	"github.com/alexandremahdhaoui/forge/pkg/mcpserver"
	"github.com/alexandremahdhaoui/forge/pkg/mcptypes"
	"github.com/alexandremahdhaoui/forge/pkg/mcputil"
	"github.com/modelcontextprotocol/go-sdk/mcp"
)

// InstallFunc is the handler signature for the install tool.
// Lay fetched archives out under the prefix per the description's strip and picks. Writes under the prefix and nowhere else.
type InstallFunc func(
	ctx context.Context,
	input InstallInput,
) (*InstallOutput, error)

// Handlers holds one implementation per tool declared in forge-dev.yaml.
// Every field is required. A nil field makes SetupMCPServer return an error
// rather than registering a tool that panics when called.
type Handlers struct {
	// Install implements the install tool.
	Install InstallFunc
}

// SetupMCPServer creates the MCP server and registers every declared tool plus
// config-validate.
func SetupMCPServer(name string, version string, handlers Handlers) (*mcpserver.Server, error) {
	server := mcpserver.New(name, version)

	if handlers.Install == nil {
		return nil, fmt.Errorf("Handlers.Install is required for the %q tool", "install")
	}

	mcpserver.RegisterTool(server, &mcp.Tool{
		Name:        "install",
		Description: "Lay fetched archives out under the prefix per the description's strip and picks. Writes under the prefix and nowhere else.",
	}, wrapInstall(handlers.Install))

	mcpserver.RegisterTool(server, &mcp.Tool{
		Name:        "config-validate",
		Description: fmt.Sprintf("Validate %s engine-specific spec configuration.", name),
	}, handleConfigValidate)

	return server, nil
}

// wrapInstall adapts InstallFunc to the MCP tool handler shape.
func wrapInstall(fn InstallFunc) func(
	context.Context, *mcp.CallToolRequest, InstallInput,
) (*mcp.CallToolResult, any, error) {
	return func(
		ctx context.Context,
		_ *mcp.CallToolRequest,
		input InstallInput,
	) (*mcp.CallToolResult, any, error) {
		output, err := fn(ctx, input)
		if err != nil {
			return nil, nil, err
		}

		return nil, output, nil
	}
}

// handleConfigValidate handles the config-validate MCP tool.
func handleConfigValidate(
	_ context.Context,
	_ *mcp.CallToolRequest,
	input mcptypes.ConfigValidateInput,
) (*mcp.CallToolResult, any, error) {
	output := ValidateMap(input.Spec)

	if output.Valid {
		result, artifact := mcputil.SuccessResultWithArtifact("Configuration is valid", output)

		return result, artifact, nil
	}

	result, artifact := mcputil.SuccessResultWithArtifact(
		fmt.Sprintf("Configuration validation failed with %d error(s)", len(output.Errors)),
		output,
	)

	return result, artifact, nil
}
