// Code generated by forge-dev. DO NOT EDIT.
// Source: spec.openapi.yaml
// SourceChecksum: sha256:b36e47857e1bd5258bac7a4cfa4f5004cf66a7dec4f6610b030c020592940bc5

package main

import (
	"fmt"
)

// Command represents the Command configuration.
// One command to run after a render, from the directory it names.
type Command struct {
	// Its arguments.
	Args []string `json:"args,omitempty"`
	// The executable name, resolved on PATH.
	Command string `json:"command"`
	// Where to run it. Absolute, as the engine received the paths.
	Dir string `json:"dir"`
	// Environment variables set for this command only. A go tidy needs GOWORK=off, because in workspace mode it writes no per module sums.
	Env map[string]string `json:"env,omitempty"`
	// When true a failure is reported and the sync still succeeds. A tidy needs the network, and a sync must work offline.
	Optional bool `json:"optional,omitempty"`
}

// Spec represents the Spec configuration.
// Engine specific configuration, passed through verbatim from the factory's engines entry. The fetch engine reads its rewrite rules here; a language engine needs none today.
type Spec map[string]interface{}

// RuntimePick represents the RuntimePick configuration.
// Lay the contents of one archive subtree at a path under the prefix. For a file artifact, a pick with only at renames the file - a release asset called pnpm-linux-x64 lands as pnpm.
type RuntimePick struct {
	// Destination under the install prefix. Empty is the root.
	At string `json:"at,omitempty"`
	// The subtree inside the archive, after strip. Empty is the whole tree.
	From string `json:"from,omitempty"`
}

// FetchOutput represents the FetchOutput configuration.
// Where the verified bytes landed.
type FetchOutput struct {
	Path string `json:"path"`
	// The hash actually computed. Equal to the artifact's or the fetch failed.
	Sha256 string `json:"sha256"`
}

// File represents the File configuration.
// One file an engine wants written.
type File struct {
	// More names to ignore in the same repo. A tidy writes go.sum beside the generated go.mod, and a derived file is never committed either.
	AlsoIgnore []string `json:"alsoIgnore,omitempty"`
	// The whole file. Engines render whole files, never fragments.
	Content string `json:"content"`
	// The repo whose .gitignore must carry this path, relative to that repo. Empty when the file is not generated into a repo.
	Gitignore string `json:"gitignore,omitempty"`
	// Absolute path.
	Path string `json:"path"`
}

// InstallOutput represents the InstallOutput configuration.
// What was laid out, prefix-relative.
type InstallOutput struct {
	Installed []string `json:"installed"`
}

// LanguageOutput represents the LanguageOutput configuration.
// Which language an engine speaks, so forge-factory can route to it.
type LanguageOutput struct {
	// The language name matched against a repo's languages list.
	Language string `json:"language"`
}

// Repo represents the Repo configuration.
// One member of the workspace.
type Repo struct {
	// What the repo declares about itself in its forge.yaml factory block. Keys are the engine's business. forge-factory copies them through without reading any of them.
	Identity map[string]string `json:"identity,omitempty"`
	// Languages this repo is written in.
	Languages []string `json:"languages,omitempty"`
	// Directory name under the workspace root.
	Name string `json:"name"`
	// Absolute path to the repo.
	Path string `json:"path"`
}

// RuntimePrerequisite represents the RuntimePrerequisite configuration.
// Something this runtime assumes about the machine and cannot carry itself. Declared so it is verified and named, never guessed: the resolver satisfies it from another declared runtime that provides it, or verifies it on the host, or fails loud - it never installs into the host.
type RuntimePrerequisite struct {
	// A capability name, matched against other runtimes' provides.
	Name string `json:"name"`
	// Why, for the human reading the refusal. Names the feature that needs it.
	Reason string `json:"reason"`
	// An executable name whose presence on PATH satisfies the check when no declared runtime provides the capability. Empty means only a providing runtime can satisfy it.
	Verify string `json:"verify,omitempty"`
}

// DescribeInput represents the DescribeInput configuration.
// What a provider engine is asked when the factory declares a runtime. The engine answers pure data - where the bytes live and how they lay out - and touches nothing. os and arch use Go's naming (linux, darwin; amd64, arm64), because every engine in this fleet already speaks it.
type DescribeInput struct {
	Arch string `json:"arch"`
	Os   string `json:"os"`
	// Extra keys from the runtime's factory entry, passed through verbatim. A generic provider parameterizes on them - the JRE's source vendor, for example. A language provider may ignore them.
	Params map[string]string `json:"params,omitempty"`
	// The declared runtime name, which is also the engine's alias.
	Runtime string `json:"runtime"`
	Spec    Spec   `json:"spec,omitempty"`
	// The pinned version, exactly as the factory declares it.
	Version string `json:"version"`
}

// RuntimeArtifact represents the RuntimeArtifact configuration.
// One archive to fetch and lay out. The sha256 is the whole trust model - however the bytes arrive (upstream, a mirror, a seeded cache), they must hash to this - so a description without one is invalid by schema.
type RuntimeArtifact struct {
	// Subtrees to lay out, applied after strip. Empty means the whole tree lands at the prefix root. Rust's component tarballs need this - rustc/, cargo/ and rust-std-*/ each merge INTO the one prefix, which is what its install script does imperatively and this expresses as data.
	Picks  []RuntimePick `json:"picks,omitempty"`
	Sha256 string        `json:"sha256"`
	// Leading path components dropped while unpacking. Default 0.
	Strip int `json:"strip,omitempty"`
	// How the install engine opens it. file means a single executable written as-is - a standalone binary like pnpm needs no archive. Every pinned distribution publishes one of these; xz stays out until an artifact exists that ships nothing else.
	Unpack string `json:"unpack"`
	// Where the bytes live. The fetch engine may rewrite the prefix (a mirror, an internal artifact store); the hash still decides.
	Url string `json:"url"`
}

// RenderOutput represents the RenderOutput configuration.
// What an engine decided to write.
type RenderOutput struct {
	// The commands that resolve this language's dependency closure into its lockfile, in order. A generated manifest names only the direct requires the factory declares; these commands put the indirect ones and the integrity sums back. Only a language engine knows them, and only the build phase runs them.
	DependencyLock []Command `json:"dependencyLock,omitempty"`
	Files          []File    `json:"files"`
	// The files the dependency-lock commands resolve into, absolute as the engine received the paths. Only a language engine knows their names; the caller hashes and records them so a revision carries the exact closure it was proven with, without ever learning what the files mean.
	Lockfiles []string `json:"lockfiles,omitempty"`
}

// RenderInput represents the RenderInput configuration.
// Everything an engine needs to decide what to write.
type RenderInput struct {
	// Dependency name to version, for this engine's language only.
	Dependencies map[string]string `json:"dependencies,omitempty"`
	// What only the tests and the tooling need, for this engine's language only. Kept apart because a published package must not carry them.
	DevDependencies map[string]string `json:"devDependencies,omitempty"`
	// Every member, including those in other languages.
	Repos []Repo `json:"repos"`
	// The workspace root, where cross repo files live.
	Root string `json:"root"`
	Spec Spec   `json:"spec,omitempty"`
}

// FetchInput represents the FetchInput configuration.
// Bring one artifact's bytes to a local path. The fetch engine is where source customization lives - its spec rewrites url prefixes for a mirror or an internal store - and the sha256 check is not optional.
type FetchInput struct {
	Artifact RuntimeArtifact `json:"artifact"`
	// Absolute file path to write the bytes to.
	Dest string `json:"dest"`
	Spec Spec   `json:"spec,omitempty"`
}

// FetchedArchive represents the FetchedArchive configuration.
// One artifact and the local path its verified bytes sit at.
type FetchedArchive struct {
	Artifact RuntimeArtifact `json:"artifact"`
	Path     string          `json:"path"`
}

// RuntimeDescription represents the RuntimeDescription configuration.
// A provider engine's whole answer: what to fetch, how it lays out, what it exposes, what it assumes. Pure data - printable, diffable, and recordable beside the revision that used it.
type RuntimeDescription struct {
	Artifacts []RuntimeArtifact `json:"artifacts"`
	// Prefix-relative executables to expose on the workspace's .forge/bin.
	Bins []string `json:"bins,omitempty"`
	// Environment the runtime needs, composed into the managed .envrc block. The literal token {prefix} in a value is replaced with the store path at expose time - JAVA_HOME is "{prefix}", a library path is "{prefix}/lib".
	Env           map[string]string     `json:"env,omitempty"`
	Prerequisites []RuntimePrerequisite `json:"prerequisites,omitempty"`
	// Capability names this runtime satisfies for OTHER runtimes' prerequisites - zig provides c-compiler.
	Provides []string `json:"provides,omitempty"`
	Runtime  string   `json:"runtime"`
	Version  string   `json:"version"`
}

// InstallInput represents the InstallInput configuration.
// Materialize fetched archives into one prefix. The contract is containment: the install engine writes under prefix and nowhere else.
type InstallInput struct {
	Archives []FetchedArchive `json:"archives"`
	// Absolute directory to lay the runtime out in.
	Prefix string `json:"prefix"`
	Spec   Spec   `json:"spec,omitempty"`
}

// CommandFromMap creates a Command from a map[string]interface{}.
func CommandFromMap(m map[string]interface{}) (*Command, error) {
	if m == nil {
		return &Command{}, nil
	}

	s := &Command{}
	// Parse args
	if v, ok := m["args"]; ok && v != nil {
		if arr, ok := v.([]interface{}); ok {
			s.Args = make([]string, 0, len(arr))
			for i, item := range arr {
				if str, ok := item.(string); ok {
					s.Args = append(s.Args, str)
				} else {
					return nil, fmt.Errorf("field args[%d]: expected string, got %T", i, item)
				}
			}
		} else if arr, ok := v.([]string); ok {
			s.Args = arr
		} else {
			return nil, fmt.Errorf("field args: expected []string, got %T", v)
		}
	}
	// Parse command
	if v, ok := m["command"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Command = val
		} else {
			return nil, fmt.Errorf("field command: expected string, got %T", v)
		}
	}
	// Parse dir
	if v, ok := m["dir"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Dir = val
		} else {
			return nil, fmt.Errorf("field dir: expected string, got %T", v)
		}
	}
	// Parse env
	if v, ok := m["env"]; ok && v != nil {
		if mapVal, ok := v.(map[string]interface{}); ok {
			s.Env = make(map[string]string, len(mapVal))
			for key, val := range mapVal {
				if str, ok := val.(string); ok {
					s.Env[key] = str
				} else {
					return nil, fmt.Errorf("field env[%s]: expected string, got %T", key, val)
				}
			}
		} else if mapVal, ok := v.(map[string]string); ok {
			s.Env = mapVal
		} else {
			return nil, fmt.Errorf("field env: expected map[string]string, got %T", v)
		}
	}
	// Parse optional
	if v, ok := m["optional"]; ok && v != nil {
		if val, ok := v.(bool); ok {
			s.Optional = val
		} else {
			return nil, fmt.Errorf("field optional: expected bool, got %T", v)
		}
	}
	return s, nil
}

// SpecFromMap creates a Spec from a map[string]interface{}.
func SpecFromMap(m map[string]interface{}) (*Spec, error) {
	if m == nil {
		return &Spec{}, nil
	}

	s := &Spec{}
	return s, nil
}

// RuntimePickFromMap creates a RuntimePick from a map[string]interface{}.
func RuntimePickFromMap(m map[string]interface{}) (*RuntimePick, error) {
	if m == nil {
		return &RuntimePick{}, nil
	}

	s := &RuntimePick{}
	// Parse at
	if v, ok := m["at"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.At = val
		} else {
			return nil, fmt.Errorf("field at: expected string, got %T", v)
		}
	}
	// Parse from
	if v, ok := m["from"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.From = val
		} else {
			return nil, fmt.Errorf("field from: expected string, got %T", v)
		}
	}
	return s, nil
}

// FetchOutputFromMap creates a FetchOutput from a map[string]interface{}.
func FetchOutputFromMap(m map[string]interface{}) (*FetchOutput, error) {
	if m == nil {
		return &FetchOutput{}, nil
	}

	s := &FetchOutput{}
	// Parse path
	if v, ok := m["path"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Path = val
		} else {
			return nil, fmt.Errorf("field path: expected string, got %T", v)
		}
	}
	// Parse sha256
	if v, ok := m["sha256"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Sha256 = val
		} else {
			return nil, fmt.Errorf("field sha256: expected string, got %T", v)
		}
	}
	return s, nil
}

// FileFromMap creates a File from a map[string]interface{}.
func FileFromMap(m map[string]interface{}) (*File, error) {
	if m == nil {
		return &File{}, nil
	}

	s := &File{}
	// Parse alsoIgnore
	if v, ok := m["alsoIgnore"]; ok && v != nil {
		if arr, ok := v.([]interface{}); ok {
			s.AlsoIgnore = make([]string, 0, len(arr))
			for i, item := range arr {
				if str, ok := item.(string); ok {
					s.AlsoIgnore = append(s.AlsoIgnore, str)
				} else {
					return nil, fmt.Errorf("field alsoIgnore[%d]: expected string, got %T", i, item)
				}
			}
		} else if arr, ok := v.([]string); ok {
			s.AlsoIgnore = arr
		} else {
			return nil, fmt.Errorf("field alsoIgnore: expected []string, got %T", v)
		}
	}
	// Parse content
	if v, ok := m["content"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Content = val
		} else {
			return nil, fmt.Errorf("field content: expected string, got %T", v)
		}
	}
	// Parse gitignore
	if v, ok := m["gitignore"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Gitignore = val
		} else {
			return nil, fmt.Errorf("field gitignore: expected string, got %T", v)
		}
	}
	// Parse path
	if v, ok := m["path"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Path = val
		} else {
			return nil, fmt.Errorf("field path: expected string, got %T", v)
		}
	}
	return s, nil
}

// InstallOutputFromMap creates a InstallOutput from a map[string]interface{}.
func InstallOutputFromMap(m map[string]interface{}) (*InstallOutput, error) {
	if m == nil {
		return &InstallOutput{}, nil
	}

	s := &InstallOutput{}
	// Parse installed
	if v, ok := m["installed"]; ok && v != nil {
		if arr, ok := v.([]interface{}); ok {
			s.Installed = make([]string, 0, len(arr))
			for i, item := range arr {
				if str, ok := item.(string); ok {
					s.Installed = append(s.Installed, str)
				} else {
					return nil, fmt.Errorf("field installed[%d]: expected string, got %T", i, item)
				}
			}
		} else if arr, ok := v.([]string); ok {
			s.Installed = arr
		} else {
			return nil, fmt.Errorf("field installed: expected []string, got %T", v)
		}
	}
	return s, nil
}

// LanguageOutputFromMap creates a LanguageOutput from a map[string]interface{}.
func LanguageOutputFromMap(m map[string]interface{}) (*LanguageOutput, error) {
	if m == nil {
		return &LanguageOutput{}, nil
	}

	s := &LanguageOutput{}
	// Parse language
	if v, ok := m["language"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Language = val
		} else {
			return nil, fmt.Errorf("field language: expected string, got %T", v)
		}
	}
	return s, nil
}

// RepoFromMap creates a Repo from a map[string]interface{}.
func RepoFromMap(m map[string]interface{}) (*Repo, error) {
	if m == nil {
		return &Repo{}, nil
	}

	s := &Repo{}
	// Parse identity
	if v, ok := m["identity"]; ok && v != nil {
		if mapVal, ok := v.(map[string]interface{}); ok {
			s.Identity = make(map[string]string, len(mapVal))
			for key, val := range mapVal {
				if str, ok := val.(string); ok {
					s.Identity[key] = str
				} else {
					return nil, fmt.Errorf("field identity[%s]: expected string, got %T", key, val)
				}
			}
		} else if mapVal, ok := v.(map[string]string); ok {
			s.Identity = mapVal
		} else {
			return nil, fmt.Errorf("field identity: expected map[string]string, got %T", v)
		}
	}
	// Parse languages
	if v, ok := m["languages"]; ok && v != nil {
		if arr, ok := v.([]interface{}); ok {
			s.Languages = make([]string, 0, len(arr))
			for i, item := range arr {
				if str, ok := item.(string); ok {
					s.Languages = append(s.Languages, str)
				} else {
					return nil, fmt.Errorf("field languages[%d]: expected string, got %T", i, item)
				}
			}
		} else if arr, ok := v.([]string); ok {
			s.Languages = arr
		} else {
			return nil, fmt.Errorf("field languages: expected []string, got %T", v)
		}
	}
	// Parse name
	if v, ok := m["name"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Name = val
		} else {
			return nil, fmt.Errorf("field name: expected string, got %T", v)
		}
	}
	// Parse path
	if v, ok := m["path"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Path = val
		} else {
			return nil, fmt.Errorf("field path: expected string, got %T", v)
		}
	}
	return s, nil
}

// RuntimePrerequisiteFromMap creates a RuntimePrerequisite from a map[string]interface{}.
func RuntimePrerequisiteFromMap(m map[string]interface{}) (*RuntimePrerequisite, error) {
	if m == nil {
		return &RuntimePrerequisite{}, nil
	}

	s := &RuntimePrerequisite{}
	// Parse name
	if v, ok := m["name"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Name = val
		} else {
			return nil, fmt.Errorf("field name: expected string, got %T", v)
		}
	}
	// Parse reason
	if v, ok := m["reason"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Reason = val
		} else {
			return nil, fmt.Errorf("field reason: expected string, got %T", v)
		}
	}
	// Parse verify
	if v, ok := m["verify"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Verify = val
		} else {
			return nil, fmt.Errorf("field verify: expected string, got %T", v)
		}
	}
	return s, nil
}

// DescribeInputFromMap creates a DescribeInput from a map[string]interface{}.
func DescribeInputFromMap(m map[string]interface{}) (*DescribeInput, error) {
	if m == nil {
		return &DescribeInput{}, nil
	}

	s := &DescribeInput{}
	// Parse arch
	if v, ok := m["arch"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Arch = val
		} else {
			return nil, fmt.Errorf("field arch: expected string, got %T", v)
		}
	}
	// Parse os
	if v, ok := m["os"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Os = val
		} else {
			return nil, fmt.Errorf("field os: expected string, got %T", v)
		}
	}
	// Parse params
	if v, ok := m["params"]; ok && v != nil {
		if mapVal, ok := v.(map[string]interface{}); ok {
			s.Params = make(map[string]string, len(mapVal))
			for key, val := range mapVal {
				if str, ok := val.(string); ok {
					s.Params[key] = str
				} else {
					return nil, fmt.Errorf("field params[%s]: expected string, got %T", key, val)
				}
			}
		} else if mapVal, ok := v.(map[string]string); ok {
			s.Params = mapVal
		} else {
			return nil, fmt.Errorf("field params: expected map[string]string, got %T", v)
		}
	}
	// Parse runtime
	if v, ok := m["runtime"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Runtime = val
		} else {
			return nil, fmt.Errorf("field runtime: expected string, got %T", v)
		}
	}
	// Parse spec
	if v, ok := m["spec"]; ok && v != nil {
		if obj, ok := v.(map[string]interface{}); ok {
			ref, err := SpecFromMap(obj)
			if err != nil {
				return nil, fmt.Errorf("field spec: %w", err)
			}
			if ref != nil {
				s.Spec = *ref
			}
		} else {
			return nil, fmt.Errorf("field spec: expected object, got %T", v)
		}
	}
	// Parse version
	if v, ok := m["version"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Version = val
		} else {
			return nil, fmt.Errorf("field version: expected string, got %T", v)
		}
	}
	return s, nil
}

// RuntimeArtifactFromMap creates a RuntimeArtifact from a map[string]interface{}.
func RuntimeArtifactFromMap(m map[string]interface{}) (*RuntimeArtifact, error) {
	if m == nil {
		return &RuntimeArtifact{}, nil
	}

	s := &RuntimeArtifact{}
	// Parse picks
	if v, ok := m["picks"]; ok && v != nil {
		if arr, ok := v.([]interface{}); ok {
			s.Picks = make([]RuntimePick, 0, len(arr))
			for i, item := range arr {
				if obj, ok := item.(map[string]interface{}); ok {
					ref, err := RuntimePickFromMap(obj)
					if err != nil {
						return nil, fmt.Errorf("field picks[%d]: %w", i, err)
					}
					if ref != nil {
						s.Picks = append(s.Picks, *ref)
					}
				} else {
					return nil, fmt.Errorf("field picks[%d]: expected object, got %T", i, item)
				}
			}
		} else {
			return nil, fmt.Errorf("field picks: expected []object, got %T", v)
		}
	}
	// Parse sha256
	if v, ok := m["sha256"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Sha256 = val
		} else {
			return nil, fmt.Errorf("field sha256: expected string, got %T", v)
		}
	}
	// Parse strip
	if v, ok := m["strip"]; ok && v != nil {
		switch val := v.(type) {
		case int:
			s.Strip = val
		case int64:
			s.Strip = int(val)
		case float64:
			s.Strip = int(val)
		default:
			return nil, fmt.Errorf("field strip: expected int, got %T", v)
		}
	}
	// Parse unpack
	if v, ok := m["unpack"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Unpack = val
		} else {
			return nil, fmt.Errorf("field unpack: expected string, got %T", v)
		}
	}
	// Parse url
	if v, ok := m["url"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Url = val
		} else {
			return nil, fmt.Errorf("field url: expected string, got %T", v)
		}
	}
	return s, nil
}

// RenderOutputFromMap creates a RenderOutput from a map[string]interface{}.
func RenderOutputFromMap(m map[string]interface{}) (*RenderOutput, error) {
	if m == nil {
		return &RenderOutput{}, nil
	}

	s := &RenderOutput{}
	// Parse dependencyLock
	if v, ok := m["dependencyLock"]; ok && v != nil {
		if arr, ok := v.([]interface{}); ok {
			s.DependencyLock = make([]Command, 0, len(arr))
			for i, item := range arr {
				if obj, ok := item.(map[string]interface{}); ok {
					ref, err := CommandFromMap(obj)
					if err != nil {
						return nil, fmt.Errorf("field dependencyLock[%d]: %w", i, err)
					}
					if ref != nil {
						s.DependencyLock = append(s.DependencyLock, *ref)
					}
				} else {
					return nil, fmt.Errorf("field dependencyLock[%d]: expected object, got %T", i, item)
				}
			}
		} else {
			return nil, fmt.Errorf("field dependencyLock: expected []object, got %T", v)
		}
	}
	// Parse files
	if v, ok := m["files"]; ok && v != nil {
		if arr, ok := v.([]interface{}); ok {
			s.Files = make([]File, 0, len(arr))
			for i, item := range arr {
				if obj, ok := item.(map[string]interface{}); ok {
					ref, err := FileFromMap(obj)
					if err != nil {
						return nil, fmt.Errorf("field files[%d]: %w", i, err)
					}
					if ref != nil {
						s.Files = append(s.Files, *ref)
					}
				} else {
					return nil, fmt.Errorf("field files[%d]: expected object, got %T", i, item)
				}
			}
		} else {
			return nil, fmt.Errorf("field files: expected []object, got %T", v)
		}
	}
	// Parse lockfiles
	if v, ok := m["lockfiles"]; ok && v != nil {
		if arr, ok := v.([]interface{}); ok {
			s.Lockfiles = make([]string, 0, len(arr))
			for i, item := range arr {
				if str, ok := item.(string); ok {
					s.Lockfiles = append(s.Lockfiles, str)
				} else {
					return nil, fmt.Errorf("field lockfiles[%d]: expected string, got %T", i, item)
				}
			}
		} else if arr, ok := v.([]string); ok {
			s.Lockfiles = arr
		} else {
			return nil, fmt.Errorf("field lockfiles: expected []string, got %T", v)
		}
	}
	return s, nil
}

// RenderInputFromMap creates a RenderInput from a map[string]interface{}.
func RenderInputFromMap(m map[string]interface{}) (*RenderInput, error) {
	if m == nil {
		return &RenderInput{}, nil
	}

	s := &RenderInput{}
	// Parse dependencies
	if v, ok := m["dependencies"]; ok && v != nil {
		if mapVal, ok := v.(map[string]interface{}); ok {
			s.Dependencies = make(map[string]string, len(mapVal))
			for key, val := range mapVal {
				if str, ok := val.(string); ok {
					s.Dependencies[key] = str
				} else {
					return nil, fmt.Errorf("field dependencies[%s]: expected string, got %T", key, val)
				}
			}
		} else if mapVal, ok := v.(map[string]string); ok {
			s.Dependencies = mapVal
		} else {
			return nil, fmt.Errorf("field dependencies: expected map[string]string, got %T", v)
		}
	}
	// Parse devDependencies
	if v, ok := m["devDependencies"]; ok && v != nil {
		if mapVal, ok := v.(map[string]interface{}); ok {
			s.DevDependencies = make(map[string]string, len(mapVal))
			for key, val := range mapVal {
				if str, ok := val.(string); ok {
					s.DevDependencies[key] = str
				} else {
					return nil, fmt.Errorf("field devDependencies[%s]: expected string, got %T", key, val)
				}
			}
		} else if mapVal, ok := v.(map[string]string); ok {
			s.DevDependencies = mapVal
		} else {
			return nil, fmt.Errorf("field devDependencies: expected map[string]string, got %T", v)
		}
	}
	// Parse repos
	if v, ok := m["repos"]; ok && v != nil {
		if arr, ok := v.([]interface{}); ok {
			s.Repos = make([]Repo, 0, len(arr))
			for i, item := range arr {
				if obj, ok := item.(map[string]interface{}); ok {
					ref, err := RepoFromMap(obj)
					if err != nil {
						return nil, fmt.Errorf("field repos[%d]: %w", i, err)
					}
					if ref != nil {
						s.Repos = append(s.Repos, *ref)
					}
				} else {
					return nil, fmt.Errorf("field repos[%d]: expected object, got %T", i, item)
				}
			}
		} else {
			return nil, fmt.Errorf("field repos: expected []object, got %T", v)
		}
	}
	// Parse root
	if v, ok := m["root"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Root = val
		} else {
			return nil, fmt.Errorf("field root: expected string, got %T", v)
		}
	}
	// Parse spec
	if v, ok := m["spec"]; ok && v != nil {
		if obj, ok := v.(map[string]interface{}); ok {
			ref, err := SpecFromMap(obj)
			if err != nil {
				return nil, fmt.Errorf("field spec: %w", err)
			}
			if ref != nil {
				s.Spec = *ref
			}
		} else {
			return nil, fmt.Errorf("field spec: expected object, got %T", v)
		}
	}
	return s, nil
}

// FetchInputFromMap creates a FetchInput from a map[string]interface{}.
func FetchInputFromMap(m map[string]interface{}) (*FetchInput, error) {
	if m == nil {
		return &FetchInput{}, nil
	}

	s := &FetchInput{}
	// Parse artifact
	if v, ok := m["artifact"]; ok && v != nil {
		if obj, ok := v.(map[string]interface{}); ok {
			ref, err := RuntimeArtifactFromMap(obj)
			if err != nil {
				return nil, fmt.Errorf("field artifact: %w", err)
			}
			if ref != nil {
				s.Artifact = *ref
			}
		} else {
			return nil, fmt.Errorf("field artifact: expected object, got %T", v)
		}
	}
	// Parse dest
	if v, ok := m["dest"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Dest = val
		} else {
			return nil, fmt.Errorf("field dest: expected string, got %T", v)
		}
	}
	// Parse spec
	if v, ok := m["spec"]; ok && v != nil {
		if obj, ok := v.(map[string]interface{}); ok {
			ref, err := SpecFromMap(obj)
			if err != nil {
				return nil, fmt.Errorf("field spec: %w", err)
			}
			if ref != nil {
				s.Spec = *ref
			}
		} else {
			return nil, fmt.Errorf("field spec: expected object, got %T", v)
		}
	}
	return s, nil
}

// FetchedArchiveFromMap creates a FetchedArchive from a map[string]interface{}.
func FetchedArchiveFromMap(m map[string]interface{}) (*FetchedArchive, error) {
	if m == nil {
		return &FetchedArchive{}, nil
	}

	s := &FetchedArchive{}
	// Parse artifact
	if v, ok := m["artifact"]; ok && v != nil {
		if obj, ok := v.(map[string]interface{}); ok {
			ref, err := RuntimeArtifactFromMap(obj)
			if err != nil {
				return nil, fmt.Errorf("field artifact: %w", err)
			}
			if ref != nil {
				s.Artifact = *ref
			}
		} else {
			return nil, fmt.Errorf("field artifact: expected object, got %T", v)
		}
	}
	// Parse path
	if v, ok := m["path"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Path = val
		} else {
			return nil, fmt.Errorf("field path: expected string, got %T", v)
		}
	}
	return s, nil
}

// RuntimeDescriptionFromMap creates a RuntimeDescription from a map[string]interface{}.
func RuntimeDescriptionFromMap(m map[string]interface{}) (*RuntimeDescription, error) {
	if m == nil {
		return &RuntimeDescription{}, nil
	}

	s := &RuntimeDescription{}
	// Parse artifacts
	if v, ok := m["artifacts"]; ok && v != nil {
		if arr, ok := v.([]interface{}); ok {
			s.Artifacts = make([]RuntimeArtifact, 0, len(arr))
			for i, item := range arr {
				if obj, ok := item.(map[string]interface{}); ok {
					ref, err := RuntimeArtifactFromMap(obj)
					if err != nil {
						return nil, fmt.Errorf("field artifacts[%d]: %w", i, err)
					}
					if ref != nil {
						s.Artifacts = append(s.Artifacts, *ref)
					}
				} else {
					return nil, fmt.Errorf("field artifacts[%d]: expected object, got %T", i, item)
				}
			}
		} else {
			return nil, fmt.Errorf("field artifacts: expected []object, got %T", v)
		}
	}
	// Parse bins
	if v, ok := m["bins"]; ok && v != nil {
		if arr, ok := v.([]interface{}); ok {
			s.Bins = make([]string, 0, len(arr))
			for i, item := range arr {
				if str, ok := item.(string); ok {
					s.Bins = append(s.Bins, str)
				} else {
					return nil, fmt.Errorf("field bins[%d]: expected string, got %T", i, item)
				}
			}
		} else if arr, ok := v.([]string); ok {
			s.Bins = arr
		} else {
			return nil, fmt.Errorf("field bins: expected []string, got %T", v)
		}
	}
	// Parse env
	if v, ok := m["env"]; ok && v != nil {
		if mapVal, ok := v.(map[string]interface{}); ok {
			s.Env = make(map[string]string, len(mapVal))
			for key, val := range mapVal {
				if str, ok := val.(string); ok {
					s.Env[key] = str
				} else {
					return nil, fmt.Errorf("field env[%s]: expected string, got %T", key, val)
				}
			}
		} else if mapVal, ok := v.(map[string]string); ok {
			s.Env = mapVal
		} else {
			return nil, fmt.Errorf("field env: expected map[string]string, got %T", v)
		}
	}
	// Parse prerequisites
	if v, ok := m["prerequisites"]; ok && v != nil {
		if arr, ok := v.([]interface{}); ok {
			s.Prerequisites = make([]RuntimePrerequisite, 0, len(arr))
			for i, item := range arr {
				if obj, ok := item.(map[string]interface{}); ok {
					ref, err := RuntimePrerequisiteFromMap(obj)
					if err != nil {
						return nil, fmt.Errorf("field prerequisites[%d]: %w", i, err)
					}
					if ref != nil {
						s.Prerequisites = append(s.Prerequisites, *ref)
					}
				} else {
					return nil, fmt.Errorf("field prerequisites[%d]: expected object, got %T", i, item)
				}
			}
		} else {
			return nil, fmt.Errorf("field prerequisites: expected []object, got %T", v)
		}
	}
	// Parse provides
	if v, ok := m["provides"]; ok && v != nil {
		if arr, ok := v.([]interface{}); ok {
			s.Provides = make([]string, 0, len(arr))
			for i, item := range arr {
				if str, ok := item.(string); ok {
					s.Provides = append(s.Provides, str)
				} else {
					return nil, fmt.Errorf("field provides[%d]: expected string, got %T", i, item)
				}
			}
		} else if arr, ok := v.([]string); ok {
			s.Provides = arr
		} else {
			return nil, fmt.Errorf("field provides: expected []string, got %T", v)
		}
	}
	// Parse runtime
	if v, ok := m["runtime"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Runtime = val
		} else {
			return nil, fmt.Errorf("field runtime: expected string, got %T", v)
		}
	}
	// Parse version
	if v, ok := m["version"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Version = val
		} else {
			return nil, fmt.Errorf("field version: expected string, got %T", v)
		}
	}
	return s, nil
}

// InstallInputFromMap creates a InstallInput from a map[string]interface{}.
func InstallInputFromMap(m map[string]interface{}) (*InstallInput, error) {
	if m == nil {
		return &InstallInput{}, nil
	}

	s := &InstallInput{}
	// Parse archives
	if v, ok := m["archives"]; ok && v != nil {
		if arr, ok := v.([]interface{}); ok {
			s.Archives = make([]FetchedArchive, 0, len(arr))
			for i, item := range arr {
				if obj, ok := item.(map[string]interface{}); ok {
					ref, err := FetchedArchiveFromMap(obj)
					if err != nil {
						return nil, fmt.Errorf("field archives[%d]: %w", i, err)
					}
					if ref != nil {
						s.Archives = append(s.Archives, *ref)
					}
				} else {
					return nil, fmt.Errorf("field archives[%d]: expected object, got %T", i, item)
				}
			}
		} else {
			return nil, fmt.Errorf("field archives: expected []object, got %T", v)
		}
	}
	// Parse prefix
	if v, ok := m["prefix"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Prefix = val
		} else {
			return nil, fmt.Errorf("field prefix: expected string, got %T", v)
		}
	}
	// Parse spec
	if v, ok := m["spec"]; ok && v != nil {
		if obj, ok := v.(map[string]interface{}); ok {
			ref, err := SpecFromMap(obj)
			if err != nil {
				return nil, fmt.Errorf("field spec: %w", err)
			}
			if ref != nil {
				s.Spec = *ref
			}
		} else {
			return nil, fmt.Errorf("field spec: expected object, got %T", v)
		}
	}
	return s, nil
}

// ToMap converts a Command to a map[string]interface{}.
func (s *Command) ToMap() map[string]interface{} {
	if s == nil {
		return nil
	}

	m := make(map[string]interface{})
	if len(s.Args) > 0 {
		m["args"] = s.Args
	}
	if s.Command != "" {
		m["command"] = s.Command
	}
	if s.Dir != "" {
		m["dir"] = s.Dir
	}
	if len(s.Env) > 0 {
		m["env"] = s.Env
	}
	if s.Optional {
		m["optional"] = s.Optional
	}
	return m
}

// ToMap converts a Spec to a map[string]interface{}.
func (s *Spec) ToMap() map[string]interface{} {
	if s == nil {
		return nil
	}

	m := make(map[string]interface{})
	return m
}

// ToMap converts a RuntimePick to a map[string]interface{}.
func (s *RuntimePick) ToMap() map[string]interface{} {
	if s == nil {
		return nil
	}

	m := make(map[string]interface{})
	if s.At != "" {
		m["at"] = s.At
	}
	if s.From != "" {
		m["from"] = s.From
	}
	return m
}

// ToMap converts a FetchOutput to a map[string]interface{}.
func (s *FetchOutput) ToMap() map[string]interface{} {
	if s == nil {
		return nil
	}

	m := make(map[string]interface{})
	if s.Path != "" {
		m["path"] = s.Path
	}
	if s.Sha256 != "" {
		m["sha256"] = s.Sha256
	}
	return m
}

// ToMap converts a File to a map[string]interface{}.
func (s *File) ToMap() map[string]interface{} {
	if s == nil {
		return nil
	}

	m := make(map[string]interface{})
	if len(s.AlsoIgnore) > 0 {
		m["alsoIgnore"] = s.AlsoIgnore
	}
	if s.Content != "" {
		m["content"] = s.Content
	}
	if s.Gitignore != "" {
		m["gitignore"] = s.Gitignore
	}
	if s.Path != "" {
		m["path"] = s.Path
	}
	return m
}

// ToMap converts a InstallOutput to a map[string]interface{}.
func (s *InstallOutput) ToMap() map[string]interface{} {
	if s == nil {
		return nil
	}

	m := make(map[string]interface{})
	if len(s.Installed) > 0 {
		m["installed"] = s.Installed
	}
	return m
}

// ToMap converts a LanguageOutput to a map[string]interface{}.
func (s *LanguageOutput) ToMap() map[string]interface{} {
	if s == nil {
		return nil
	}

	m := make(map[string]interface{})
	if s.Language != "" {
		m["language"] = s.Language
	}
	return m
}

// ToMap converts a Repo to a map[string]interface{}.
func (s *Repo) ToMap() map[string]interface{} {
	if s == nil {
		return nil
	}

	m := make(map[string]interface{})
	if len(s.Identity) > 0 {
		m["identity"] = s.Identity
	}
	if len(s.Languages) > 0 {
		m["languages"] = s.Languages
	}
	if s.Name != "" {
		m["name"] = s.Name
	}
	if s.Path != "" {
		m["path"] = s.Path
	}
	return m
}

// ToMap converts a RuntimePrerequisite to a map[string]interface{}.
func (s *RuntimePrerequisite) ToMap() map[string]interface{} {
	if s == nil {
		return nil
	}

	m := make(map[string]interface{})
	if s.Name != "" {
		m["name"] = s.Name
	}
	if s.Reason != "" {
		m["reason"] = s.Reason
	}
	if s.Verify != "" {
		m["verify"] = s.Verify
	}
	return m
}

// ToMap converts a DescribeInput to a map[string]interface{}.
func (s *DescribeInput) ToMap() map[string]interface{} {
	if s == nil {
		return nil
	}

	m := make(map[string]interface{})
	if s.Arch != "" {
		m["arch"] = s.Arch
	}
	if s.Os != "" {
		m["os"] = s.Os
	}
	if len(s.Params) > 0 {
		m["params"] = s.Params
	}
	if s.Runtime != "" {
		m["runtime"] = s.Runtime
	}
	// Reference type Spec
	if refMap := s.Spec.ToMap(); len(refMap) > 0 {
		m["spec"] = refMap
	}
	if s.Version != "" {
		m["version"] = s.Version
	}
	return m
}

// ToMap converts a RuntimeArtifact to a map[string]interface{}.
func (s *RuntimeArtifact) ToMap() map[string]interface{} {
	if s == nil {
		return nil
	}

	m := make(map[string]interface{})
	if len(s.Picks) > 0 {
		arr := make([]interface{}, 0, len(s.Picks))
		for _, item := range s.Picks {
			arr = append(arr, item.ToMap())
		}
		m["picks"] = arr
	}
	if s.Sha256 != "" {
		m["sha256"] = s.Sha256
	}
	if s.Strip != 0 {
		m["strip"] = s.Strip
	}
	if s.Unpack != "" {
		m["unpack"] = s.Unpack
	}
	if s.Url != "" {
		m["url"] = s.Url
	}
	return m
}

// ToMap converts a RenderOutput to a map[string]interface{}.
func (s *RenderOutput) ToMap() map[string]interface{} {
	if s == nil {
		return nil
	}

	m := make(map[string]interface{})
	if len(s.DependencyLock) > 0 {
		arr := make([]interface{}, 0, len(s.DependencyLock))
		for _, item := range s.DependencyLock {
			arr = append(arr, item.ToMap())
		}
		m["dependencyLock"] = arr
	}
	if len(s.Files) > 0 {
		arr := make([]interface{}, 0, len(s.Files))
		for _, item := range s.Files {
			arr = append(arr, item.ToMap())
		}
		m["files"] = arr
	}
	if len(s.Lockfiles) > 0 {
		m["lockfiles"] = s.Lockfiles
	}
	return m
}

// ToMap converts a RenderInput to a map[string]interface{}.
func (s *RenderInput) ToMap() map[string]interface{} {
	if s == nil {
		return nil
	}

	m := make(map[string]interface{})
	if len(s.Dependencies) > 0 {
		m["dependencies"] = s.Dependencies
	}
	if len(s.DevDependencies) > 0 {
		m["devDependencies"] = s.DevDependencies
	}
	if len(s.Repos) > 0 {
		arr := make([]interface{}, 0, len(s.Repos))
		for _, item := range s.Repos {
			arr = append(arr, item.ToMap())
		}
		m["repos"] = arr
	}
	if s.Root != "" {
		m["root"] = s.Root
	}
	// Reference type Spec
	if refMap := s.Spec.ToMap(); len(refMap) > 0 {
		m["spec"] = refMap
	}
	return m
}

// ToMap converts a FetchInput to a map[string]interface{}.
func (s *FetchInput) ToMap() map[string]interface{} {
	if s == nil {
		return nil
	}

	m := make(map[string]interface{})
	// Reference type RuntimeArtifact
	if refMap := s.Artifact.ToMap(); len(refMap) > 0 {
		m["artifact"] = refMap
	}
	if s.Dest != "" {
		m["dest"] = s.Dest
	}
	// Reference type Spec
	if refMap := s.Spec.ToMap(); len(refMap) > 0 {
		m["spec"] = refMap
	}
	return m
}

// ToMap converts a FetchedArchive to a map[string]interface{}.
func (s *FetchedArchive) ToMap() map[string]interface{} {
	if s == nil {
		return nil
	}

	m := make(map[string]interface{})
	// Reference type RuntimeArtifact
	if refMap := s.Artifact.ToMap(); len(refMap) > 0 {
		m["artifact"] = refMap
	}
	if s.Path != "" {
		m["path"] = s.Path
	}
	return m
}

// ToMap converts a RuntimeDescription to a map[string]interface{}.
func (s *RuntimeDescription) ToMap() map[string]interface{} {
	if s == nil {
		return nil
	}

	m := make(map[string]interface{})
	if len(s.Artifacts) > 0 {
		arr := make([]interface{}, 0, len(s.Artifacts))
		for _, item := range s.Artifacts {
			arr = append(arr, item.ToMap())
		}
		m["artifacts"] = arr
	}
	if len(s.Bins) > 0 {
		m["bins"] = s.Bins
	}
	if len(s.Env) > 0 {
		m["env"] = s.Env
	}
	if len(s.Prerequisites) > 0 {
		arr := make([]interface{}, 0, len(s.Prerequisites))
		for _, item := range s.Prerequisites {
			arr = append(arr, item.ToMap())
		}
		m["prerequisites"] = arr
	}
	if len(s.Provides) > 0 {
		m["provides"] = s.Provides
	}
	if s.Runtime != "" {
		m["runtime"] = s.Runtime
	}
	if s.Version != "" {
		m["version"] = s.Version
	}
	return m
}

// ToMap converts a InstallInput to a map[string]interface{}.
func (s *InstallInput) ToMap() map[string]interface{} {
	if s == nil {
		return nil
	}

	m := make(map[string]interface{})
	if len(s.Archives) > 0 {
		arr := make([]interface{}, 0, len(s.Archives))
		for _, item := range s.Archives {
			arr = append(arr, item.ToMap())
		}
		m["archives"] = arr
	}
	if s.Prefix != "" {
		m["prefix"] = s.Prefix
	}
	// Reference type Spec
	if refMap := s.Spec.ToMap(); len(refMap) > 0 {
		m["spec"] = refMap
	}
	return m
}

// FromMap creates a Spec from a map[string]interface{}.
// This is the main entry point for parsing the spec field from forge.yaml.
func FromMap(m map[string]interface{}) (*Spec, error) {
	return SpecFromMap(m)
}
