// Code generated by forge-dev. DO NOT EDIT.
// Source: spec.openapi.yaml
// SourceChecksum: sha256:0382184c399ca481b01148fa1cac7532a095b721eb64ed23b1594e0a628946ae

package main

import (
	"fmt"

	"github.com/alexandremahdhaoui/forge/pkg/mcptypes"
)

// ValidateCommand validates a Command and returns validation results.
// It checks required fields and validates enum values.
func ValidateCommand(s *Command) *mcptypes.ConfigValidateOutput {
	if s == nil {
		return &mcptypes.ConfigValidateOutput{
			Valid: true,
		}
	}

	var errors []mcptypes.ValidationError
	// Validate required field: command
	if s.Command == "" {
		errors = append(errors, mcptypes.ValidationError{
			Field:   "spec.command",
			Message: "required field is missing",
		})
	}
	// Validate required field: dir
	if s.Dir == "" {
		errors = append(errors, mcptypes.ValidationError{
			Field:   "spec.dir",
			Message: "required field is missing",
		})
	}

	if len(errors) > 0 {
		return &mcptypes.ConfigValidateOutput{
			Valid:  false,
			Errors: errors,
		}
	}

	return &mcptypes.ConfigValidateOutput{
		Valid: true,
	}
}

// ValidateFile validates a File and returns validation results.
// It checks required fields and validates enum values.
func ValidateFile(s *File) *mcptypes.ConfigValidateOutput {
	if s == nil {
		return &mcptypes.ConfigValidateOutput{
			Valid: true,
		}
	}

	var errors []mcptypes.ValidationError
	// Validate required field: content
	if s.Content == "" {
		errors = append(errors, mcptypes.ValidationError{
			Field:   "spec.content",
			Message: "required field is missing",
		})
	}
	// Validate required field: path
	if s.Path == "" {
		errors = append(errors, mcptypes.ValidationError{
			Field:   "spec.path",
			Message: "required field is missing",
		})
	}

	if len(errors) > 0 {
		return &mcptypes.ConfigValidateOutput{
			Valid:  false,
			Errors: errors,
		}
	}

	return &mcptypes.ConfigValidateOutput{
		Valid: true,
	}
}

// ValidateLanguageOutput validates a LanguageOutput and returns validation results.
// It checks required fields and validates enum values.
func ValidateLanguageOutput(s *LanguageOutput) *mcptypes.ConfigValidateOutput {
	if s == nil {
		return &mcptypes.ConfigValidateOutput{
			Valid: true,
		}
	}

	var errors []mcptypes.ValidationError
	// Validate required field: language
	if s.Language == "" {
		errors = append(errors, mcptypes.ValidationError{
			Field:   "spec.language",
			Message: "required field is missing",
		})
	}

	if len(errors) > 0 {
		return &mcptypes.ConfigValidateOutput{
			Valid:  false,
			Errors: errors,
		}
	}

	return &mcptypes.ConfigValidateOutput{
		Valid: true,
	}
}

// ValidateRepo validates a Repo and returns validation results.
// It checks required fields and validates enum values.
func ValidateRepo(s *Repo) *mcptypes.ConfigValidateOutput {
	if s == nil {
		return &mcptypes.ConfigValidateOutput{
			Valid: true,
		}
	}

	var errors []mcptypes.ValidationError
	// Validate required field: name
	if s.Name == "" {
		errors = append(errors, mcptypes.ValidationError{
			Field:   "spec.name",
			Message: "required field is missing",
		})
	}
	// Validate required field: path
	if s.Path == "" {
		errors = append(errors, mcptypes.ValidationError{
			Field:   "spec.path",
			Message: "required field is missing",
		})
	}

	if len(errors) > 0 {
		return &mcptypes.ConfigValidateOutput{
			Valid:  false,
			Errors: errors,
		}
	}

	return &mcptypes.ConfigValidateOutput{
		Valid: true,
	}
}

// ValidateSpec validates a Spec and returns validation results.
// It checks required fields and validates enum values.
func ValidateSpec(s *Spec) *mcptypes.ConfigValidateOutput {
	if s == nil {
		return &mcptypes.ConfigValidateOutput{
			Valid: true,
		}
	}

	var errors []mcptypes.ValidationError

	if len(errors) > 0 {
		return &mcptypes.ConfigValidateOutput{
			Valid:  false,
			Errors: errors,
		}
	}

	return &mcptypes.ConfigValidateOutput{
		Valid: true,
	}
}

// ValidateRenderOutput validates a RenderOutput and returns validation results.
// It checks required fields and validates enum values.
func ValidateRenderOutput(s *RenderOutput) *mcptypes.ConfigValidateOutput {
	if s == nil {
		return &mcptypes.ConfigValidateOutput{
			Valid: true,
		}
	}

	var errors []mcptypes.ValidationError
	// Validate required array of references: files
	if len(s.Files) == 0 {
		errors = append(errors, mcptypes.ValidationError{
			Field:   "spec.files",
			Message: "required field is missing or empty",
		})
	}
	// Validate array of references: files
	for i, item := range s.Files {
		nestedResult := ValidateFile(&item)
		if !nestedResult.Valid {
			for _, e := range nestedResult.Errors {
				errors = append(errors, mcptypes.ValidationError{
					Field:   fmt.Sprintf("spec.files[%d].%s", i, e.Field),
					Message: e.Message,
				})
			}
		}
	}
	// Validate array of references: settle
	for i, item := range s.Settle {
		nestedResult := ValidateCommand(&item)
		if !nestedResult.Valid {
			for _, e := range nestedResult.Errors {
				errors = append(errors, mcptypes.ValidationError{
					Field:   fmt.Sprintf("spec.settle[%d].%s", i, e.Field),
					Message: e.Message,
				})
			}
		}
	}

	if len(errors) > 0 {
		return &mcptypes.ConfigValidateOutput{
			Valid:  false,
			Errors: errors,
		}
	}

	return &mcptypes.ConfigValidateOutput{
		Valid: true,
	}
}

// ValidateRenderInput validates a RenderInput and returns validation results.
// It checks required fields and validates enum values.
func ValidateRenderInput(s *RenderInput) *mcptypes.ConfigValidateOutput {
	if s == nil {
		return &mcptypes.ConfigValidateOutput{
			Valid: true,
		}
	}

	var errors []mcptypes.ValidationError
	// Validate required array of references: repos
	if len(s.Repos) == 0 {
		errors = append(errors, mcptypes.ValidationError{
			Field:   "spec.repos",
			Message: "required field is missing or empty",
		})
	}
	// Validate array of references: repos
	for i, item := range s.Repos {
		nestedResult := ValidateRepo(&item)
		if !nestedResult.Valid {
			for _, e := range nestedResult.Errors {
				errors = append(errors, mcptypes.ValidationError{
					Field:   fmt.Sprintf("spec.repos[%d].%s", i, e.Field),
					Message: e.Message,
				})
			}
		}
	}
	// Validate required field: root
	if s.Root == "" {
		errors = append(errors, mcptypes.ValidationError{
			Field:   "spec.root",
			Message: "required field is missing",
		})
	}
	// Validate nested reference: spec
	{
		nested := s.Spec
		nestedResult := ValidateSpec(&nested)
		if !nestedResult.Valid {
			for _, e := range nestedResult.Errors {
				errors = append(errors, mcptypes.ValidationError{
					Field:   "spec.spec." + e.Field,
					Message: e.Message,
				})
			}
		}
	}

	if len(errors) > 0 {
		return &mcptypes.ConfigValidateOutput{
			Valid:  false,
			Errors: errors,
		}
	}

	return &mcptypes.ConfigValidateOutput{
		Valid: true,
	}
}

// Validate validates a Spec and returns validation results.
// This is the main entry point for validation.
func Validate(s *Spec) *mcptypes.ConfigValidateOutput {
	return ValidateSpec(s)
}

// ValidateMap validates a map[string]interface{} by first parsing it to a Spec.
// This is a convenience function for validating spec data from forge.yaml.
func ValidateMap(m map[string]interface{}) *mcptypes.ConfigValidateOutput {
	s, err := FromMap(m)
	if err != nil {
		return &mcptypes.ConfigValidateOutput{
			Valid: false,
			Errors: []mcptypes.ValidationError{
				{
					Field:   "spec",
					Message: err.Error(),
				},
			},
		}
	}

	return Validate(s)
}
