// Code generated by forge-dev. DO NOT EDIT.
// Source: spec.openapi.yaml
// SourceChecksum: sha256:0382184c399ca481b01148fa1cac7532a095b721eb64ed23b1594e0a628946ae

package main

import (
	"fmt"
)

// Command represents the Command configuration.
// One command to run after a render, from the directory it names.
type Command struct {
	// Its arguments.
	Args []string `json:"args,omitempty"`
	// The executable name, resolved on PATH.
	Command string `json:"command"`
	// Where to run it. Absolute, as the engine received the paths.
	Dir string `json:"dir"`
	// Environment variables set for this command only. A go tidy needs GOWORK=off, because in workspace mode it writes no per module sums.
	Env map[string]string `json:"env,omitempty"`
	// When true a failure is reported and the sync still succeeds. A tidy needs the network, and a sync must work offline.
	Optional bool `json:"optional,omitempty"`
}

// File represents the File configuration.
// One file an engine wants written.
type File struct {
	// More names to ignore in the same repo. A tidy writes go.sum beside the generated go.mod, and a derived file is never committed either.
	AlsoIgnore []string `json:"alsoIgnore,omitempty"`
	// The whole file. Engines render whole files, never fragments.
	Content string `json:"content"`
	// The repo whose .gitignore must carry this path, relative to that repo. Empty when the file is not generated into a repo.
	Gitignore string `json:"gitignore,omitempty"`
	// Absolute path.
	Path string `json:"path"`
}

// LanguageOutput represents the LanguageOutput configuration.
// Which language an engine speaks, so forge-factory can route to it.
type LanguageOutput struct {
	// The language name matched against a repo's languages list.
	Language string `json:"language"`
}

// Repo represents the Repo configuration.
// One member of the workspace.
type Repo struct {
	// What the repo declares about itself in its forge.yaml factory block. Keys are the engine's business. forge-factory copies them through without reading any of them.
	Identity map[string]string `json:"identity,omitempty"`
	// Languages this repo is written in.
	Languages []string `json:"languages,omitempty"`
	// Directory name under the workspace root.
	Name string `json:"name"`
	// Absolute path to the repo.
	Path string `json:"path"`
}

// Spec represents the Spec configuration.
// Engine specific configuration. No language engine needs any today.
type Spec struct {
}

// RenderOutput represents the RenderOutput configuration.
// What an engine decided to write.
type RenderOutput struct {
	Files []File `json:"files"`
	// What to run after the files are written, in order. A generated go.mod names only the direct requires the factory declares, so a tidy is what puts the indirect ones and the sums back.
	Settle []Command `json:"settle,omitempty"`
}

// RenderInput represents the RenderInput configuration.
// Everything an engine needs to decide what to write.
type RenderInput struct {
	// Dependency name to version, for this engine's language only.
	Dependencies map[string]string `json:"dependencies,omitempty"`
	// Every member, including those in other languages.
	Repos []Repo `json:"repos"`
	// The workspace root, where cross repo files live.
	Root string `json:"root"`
	Spec Spec   `json:"spec,omitempty"`
}

// CommandFromMap creates a Command from a map[string]interface{}.
func CommandFromMap(m map[string]interface{}) (*Command, error) {
	if m == nil {
		return &Command{}, nil
	}

	s := &Command{}
	// Parse args
	if v, ok := m["args"]; ok && v != nil {
		if arr, ok := v.([]interface{}); ok {
			s.Args = make([]string, 0, len(arr))
			for i, item := range arr {
				if str, ok := item.(string); ok {
					s.Args = append(s.Args, str)
				} else {
					return nil, fmt.Errorf("field args[%d]: expected string, got %T", i, item)
				}
			}
		} else if arr, ok := v.([]string); ok {
			s.Args = arr
		} else {
			return nil, fmt.Errorf("field args: expected []string, got %T", v)
		}
	}
	// Parse command
	if v, ok := m["command"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Command = val
		} else {
			return nil, fmt.Errorf("field command: expected string, got %T", v)
		}
	}
	// Parse dir
	if v, ok := m["dir"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Dir = val
		} else {
			return nil, fmt.Errorf("field dir: expected string, got %T", v)
		}
	}
	// Parse env
	if v, ok := m["env"]; ok && v != nil {
		if mapVal, ok := v.(map[string]interface{}); ok {
			s.Env = make(map[string]string, len(mapVal))
			for key, val := range mapVal {
				if str, ok := val.(string); ok {
					s.Env[key] = str
				} else {
					return nil, fmt.Errorf("field env[%s]: expected string, got %T", key, val)
				}
			}
		} else if mapVal, ok := v.(map[string]string); ok {
			s.Env = mapVal
		} else {
			return nil, fmt.Errorf("field env: expected map[string]string, got %T", v)
		}
	}
	// Parse optional
	if v, ok := m["optional"]; ok && v != nil {
		if val, ok := v.(bool); ok {
			s.Optional = val
		} else {
			return nil, fmt.Errorf("field optional: expected bool, got %T", v)
		}
	}
	return s, nil
}

// FileFromMap creates a File from a map[string]interface{}.
func FileFromMap(m map[string]interface{}) (*File, error) {
	if m == nil {
		return &File{}, nil
	}

	s := &File{}
	// Parse alsoIgnore
	if v, ok := m["alsoIgnore"]; ok && v != nil {
		if arr, ok := v.([]interface{}); ok {
			s.AlsoIgnore = make([]string, 0, len(arr))
			for i, item := range arr {
				if str, ok := item.(string); ok {
					s.AlsoIgnore = append(s.AlsoIgnore, str)
				} else {
					return nil, fmt.Errorf("field alsoIgnore[%d]: expected string, got %T", i, item)
				}
			}
		} else if arr, ok := v.([]string); ok {
			s.AlsoIgnore = arr
		} else {
			return nil, fmt.Errorf("field alsoIgnore: expected []string, got %T", v)
		}
	}
	// Parse content
	if v, ok := m["content"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Content = val
		} else {
			return nil, fmt.Errorf("field content: expected string, got %T", v)
		}
	}
	// Parse gitignore
	if v, ok := m["gitignore"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Gitignore = val
		} else {
			return nil, fmt.Errorf("field gitignore: expected string, got %T", v)
		}
	}
	// Parse path
	if v, ok := m["path"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Path = val
		} else {
			return nil, fmt.Errorf("field path: expected string, got %T", v)
		}
	}
	return s, nil
}

// LanguageOutputFromMap creates a LanguageOutput from a map[string]interface{}.
func LanguageOutputFromMap(m map[string]interface{}) (*LanguageOutput, error) {
	if m == nil {
		return &LanguageOutput{}, nil
	}

	s := &LanguageOutput{}
	// Parse language
	if v, ok := m["language"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Language = val
		} else {
			return nil, fmt.Errorf("field language: expected string, got %T", v)
		}
	}
	return s, nil
}

// RepoFromMap creates a Repo from a map[string]interface{}.
func RepoFromMap(m map[string]interface{}) (*Repo, error) {
	if m == nil {
		return &Repo{}, nil
	}

	s := &Repo{}
	// Parse identity
	if v, ok := m["identity"]; ok && v != nil {
		if mapVal, ok := v.(map[string]interface{}); ok {
			s.Identity = make(map[string]string, len(mapVal))
			for key, val := range mapVal {
				if str, ok := val.(string); ok {
					s.Identity[key] = str
				} else {
					return nil, fmt.Errorf("field identity[%s]: expected string, got %T", key, val)
				}
			}
		} else if mapVal, ok := v.(map[string]string); ok {
			s.Identity = mapVal
		} else {
			return nil, fmt.Errorf("field identity: expected map[string]string, got %T", v)
		}
	}
	// Parse languages
	if v, ok := m["languages"]; ok && v != nil {
		if arr, ok := v.([]interface{}); ok {
			s.Languages = make([]string, 0, len(arr))
			for i, item := range arr {
				if str, ok := item.(string); ok {
					s.Languages = append(s.Languages, str)
				} else {
					return nil, fmt.Errorf("field languages[%d]: expected string, got %T", i, item)
				}
			}
		} else if arr, ok := v.([]string); ok {
			s.Languages = arr
		} else {
			return nil, fmt.Errorf("field languages: expected []string, got %T", v)
		}
	}
	// Parse name
	if v, ok := m["name"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Name = val
		} else {
			return nil, fmt.Errorf("field name: expected string, got %T", v)
		}
	}
	// Parse path
	if v, ok := m["path"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Path = val
		} else {
			return nil, fmt.Errorf("field path: expected string, got %T", v)
		}
	}
	return s, nil
}

// SpecFromMap creates a Spec from a map[string]interface{}.
func SpecFromMap(m map[string]interface{}) (*Spec, error) {
	if m == nil {
		return &Spec{}, nil
	}

	s := &Spec{}
	return s, nil
}

// RenderOutputFromMap creates a RenderOutput from a map[string]interface{}.
func RenderOutputFromMap(m map[string]interface{}) (*RenderOutput, error) {
	if m == nil {
		return &RenderOutput{}, nil
	}

	s := &RenderOutput{}
	// Parse files
	if v, ok := m["files"]; ok && v != nil {
		if arr, ok := v.([]interface{}); ok {
			s.Files = make([]File, 0, len(arr))
			for i, item := range arr {
				if obj, ok := item.(map[string]interface{}); ok {
					ref, err := FileFromMap(obj)
					if err != nil {
						return nil, fmt.Errorf("field files[%d]: %w", i, err)
					}
					if ref != nil {
						s.Files = append(s.Files, *ref)
					}
				} else {
					return nil, fmt.Errorf("field files[%d]: expected object, got %T", i, item)
				}
			}
		} else {
			return nil, fmt.Errorf("field files: expected []object, got %T", v)
		}
	}
	// Parse settle
	if v, ok := m["settle"]; ok && v != nil {
		if arr, ok := v.([]interface{}); ok {
			s.Settle = make([]Command, 0, len(arr))
			for i, item := range arr {
				if obj, ok := item.(map[string]interface{}); ok {
					ref, err := CommandFromMap(obj)
					if err != nil {
						return nil, fmt.Errorf("field settle[%d]: %w", i, err)
					}
					if ref != nil {
						s.Settle = append(s.Settle, *ref)
					}
				} else {
					return nil, fmt.Errorf("field settle[%d]: expected object, got %T", i, item)
				}
			}
		} else {
			return nil, fmt.Errorf("field settle: expected []object, got %T", v)
		}
	}
	return s, nil
}

// RenderInputFromMap creates a RenderInput from a map[string]interface{}.
func RenderInputFromMap(m map[string]interface{}) (*RenderInput, error) {
	if m == nil {
		return &RenderInput{}, nil
	}

	s := &RenderInput{}
	// Parse dependencies
	if v, ok := m["dependencies"]; ok && v != nil {
		if mapVal, ok := v.(map[string]interface{}); ok {
			s.Dependencies = make(map[string]string, len(mapVal))
			for key, val := range mapVal {
				if str, ok := val.(string); ok {
					s.Dependencies[key] = str
				} else {
					return nil, fmt.Errorf("field dependencies[%s]: expected string, got %T", key, val)
				}
			}
		} else if mapVal, ok := v.(map[string]string); ok {
			s.Dependencies = mapVal
		} else {
			return nil, fmt.Errorf("field dependencies: expected map[string]string, got %T", v)
		}
	}
	// Parse repos
	if v, ok := m["repos"]; ok && v != nil {
		if arr, ok := v.([]interface{}); ok {
			s.Repos = make([]Repo, 0, len(arr))
			for i, item := range arr {
				if obj, ok := item.(map[string]interface{}); ok {
					ref, err := RepoFromMap(obj)
					if err != nil {
						return nil, fmt.Errorf("field repos[%d]: %w", i, err)
					}
					if ref != nil {
						s.Repos = append(s.Repos, *ref)
					}
				} else {
					return nil, fmt.Errorf("field repos[%d]: expected object, got %T", i, item)
				}
			}
		} else {
			return nil, fmt.Errorf("field repos: expected []object, got %T", v)
		}
	}
	// Parse root
	if v, ok := m["root"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Root = val
		} else {
			return nil, fmt.Errorf("field root: expected string, got %T", v)
		}
	}
	// Parse spec
	if v, ok := m["spec"]; ok && v != nil {
		if obj, ok := v.(map[string]interface{}); ok {
			ref, err := SpecFromMap(obj)
			if err != nil {
				return nil, fmt.Errorf("field spec: %w", err)
			}
			if ref != nil {
				s.Spec = *ref
			}
		} else {
			return nil, fmt.Errorf("field spec: expected object, got %T", v)
		}
	}
	return s, nil
}

// ToMap converts a Command to a map[string]interface{}.
func (s *Command) ToMap() map[string]interface{} {
	if s == nil {
		return nil
	}

	m := make(map[string]interface{})
	if len(s.Args) > 0 {
		m["args"] = s.Args
	}
	if s.Command != "" {
		m["command"] = s.Command
	}
	if s.Dir != "" {
		m["dir"] = s.Dir
	}
	if len(s.Env) > 0 {
		m["env"] = s.Env
	}
	if s.Optional {
		m["optional"] = s.Optional
	}
	return m
}

// ToMap converts a File to a map[string]interface{}.
func (s *File) ToMap() map[string]interface{} {
	if s == nil {
		return nil
	}

	m := make(map[string]interface{})
	if len(s.AlsoIgnore) > 0 {
		m["alsoIgnore"] = s.AlsoIgnore
	}
	if s.Content != "" {
		m["content"] = s.Content
	}
	if s.Gitignore != "" {
		m["gitignore"] = s.Gitignore
	}
	if s.Path != "" {
		m["path"] = s.Path
	}
	return m
}

// ToMap converts a LanguageOutput to a map[string]interface{}.
func (s *LanguageOutput) ToMap() map[string]interface{} {
	if s == nil {
		return nil
	}

	m := make(map[string]interface{})
	if s.Language != "" {
		m["language"] = s.Language
	}
	return m
}

// ToMap converts a Repo to a map[string]interface{}.
func (s *Repo) ToMap() map[string]interface{} {
	if s == nil {
		return nil
	}

	m := make(map[string]interface{})
	if len(s.Identity) > 0 {
		m["identity"] = s.Identity
	}
	if len(s.Languages) > 0 {
		m["languages"] = s.Languages
	}
	if s.Name != "" {
		m["name"] = s.Name
	}
	if s.Path != "" {
		m["path"] = s.Path
	}
	return m
}

// ToMap converts a Spec to a map[string]interface{}.
func (s *Spec) ToMap() map[string]interface{} {
	if s == nil {
		return nil
	}

	m := make(map[string]interface{})
	return m
}

// ToMap converts a RenderOutput to a map[string]interface{}.
func (s *RenderOutput) ToMap() map[string]interface{} {
	if s == nil {
		return nil
	}

	m := make(map[string]interface{})
	if len(s.Files) > 0 {
		arr := make([]interface{}, 0, len(s.Files))
		for _, item := range s.Files {
			arr = append(arr, item.ToMap())
		}
		m["files"] = arr
	}
	if len(s.Settle) > 0 {
		arr := make([]interface{}, 0, len(s.Settle))
		for _, item := range s.Settle {
			arr = append(arr, item.ToMap())
		}
		m["settle"] = arr
	}
	return m
}

// ToMap converts a RenderInput to a map[string]interface{}.
func (s *RenderInput) ToMap() map[string]interface{} {
	if s == nil {
		return nil
	}

	m := make(map[string]interface{})
	if len(s.Dependencies) > 0 {
		m["dependencies"] = s.Dependencies
	}
	if len(s.Repos) > 0 {
		arr := make([]interface{}, 0, len(s.Repos))
		for _, item := range s.Repos {
			arr = append(arr, item.ToMap())
		}
		m["repos"] = arr
	}
	if s.Root != "" {
		m["root"] = s.Root
	}
	// Reference type Spec
	if refMap := s.Spec.ToMap(); len(refMap) > 0 {
		m["spec"] = refMap
	}
	return m
}

// FromMap creates a Spec from a map[string]interface{}.
// This is the main entry point for parsing the spec field from forge.yaml.
func FromMap(m map[string]interface{}) (*Spec, error) {
	return SpecFromMap(m)
}
