// Code generated by forge-dev. DO NOT EDIT.
// Source: forge-dev.yaml
// SourceChecksum: sha256:0382184c399ca481b01148fa1cac7532a095b721eb64ed23b1594e0a628946ae

package main

import (
	"github.com/alexandremahdhaoui/forge/pkg/enginedocs"
	"github.com/alexandremahdhaoui/forge/pkg/mcpserver"
)

// docsConfig is the configuration for documentation tools.
var docsConfig = &enginedocs.Config{
	EngineName:   "factory-lang-rust",
	LocalDir:     "cmd/factory-lang-rust/docs",
	BaseURL:      "https://raw.githubusercontent.com/alexandremahdhaoui/forge-factory/refs/heads/main",
	RequiredDocs: []string{"usage", "schema"},
}

// RegisterDocsMCPTools registers the docs-list and docs-get MCP tools.
func RegisterDocsMCPTools(server *mcpserver.Server) error {
	return enginedocs.RegisterDocsTools(server, *docsConfig)
}
