// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package fsadaptermock

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockFS creates a new instance of MockFS. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFS(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFS {
	mock := &MockFS{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFS is an autogenerated mock type for the FS type
type MockFS struct {
	mock.Mock
}

type MockFS_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFS) EXPECT() *MockFS_Expecter {
	return &MockFS_Expecter{mock: &_m.Mock}
}

// Exists provides a mock function for the type MockFS
func (_mock *MockFS) Exists(path string) (bool, error) {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return returnFunc(path)
	}
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(path)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFS_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type MockFS_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - path string
func (_e *MockFS_Expecter) Exists(path any) *MockFS_Exists_Call {
	return &MockFS_Exists_Call{Call: _e.mock.On("Exists", path)}
}

func (_c *MockFS_Exists_Call) Run(run func(path string)) *MockFS_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFS_Exists_Call) Return(b bool, err error) *MockFS_Exists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockFS_Exists_Call) RunAndReturn(run func(path string) (bool, error)) *MockFS_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// IsDir provides a mock function for the type MockFS
func (_mock *MockFS) IsDir(path string) (bool, error) {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for IsDir")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return returnFunc(path)
	}
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(path)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFS_IsDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsDir'
type MockFS_IsDir_Call struct {
	*mock.Call
}

// IsDir is a helper method to define mock.On call
//   - path string
func (_e *MockFS_Expecter) IsDir(path any) *MockFS_IsDir_Call {
	return &MockFS_IsDir_Call{Call: _e.mock.On("IsDir", path)}
}

func (_c *MockFS_IsDir_Call) Run(run func(path string)) *MockFS_IsDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFS_IsDir_Call) Return(b bool, err error) *MockFS_IsDir_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockFS_IsDir_Call) RunAndReturn(run func(path string) (bool, error)) *MockFS_IsDir_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockFS
func (_mock *MockFS) List(dir string) ([]string, error) {
	ret := _mock.Called(dir)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]string, error)); ok {
		return returnFunc(dir)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []string); ok {
		r0 = returnFunc(dir)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(dir)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFS_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockFS_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - dir string
func (_e *MockFS_Expecter) List(dir any) *MockFS_List_Call {
	return &MockFS_List_Call{Call: _e.mock.On("List", dir)}
}

func (_c *MockFS_List_Call) Run(run func(dir string)) *MockFS_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFS_List_Call) Return(strings []string, err error) *MockFS_List_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockFS_List_Call) RunAndReturn(run func(dir string) ([]string, error)) *MockFS_List_Call {
	_c.Call.Return(run)
	return _c
}

// MkdirAll provides a mock function for the type MockFS
func (_mock *MockFS) MkdirAll(path string) error {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for MkdirAll")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(path)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFS_MkdirAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MkdirAll'
type MockFS_MkdirAll_Call struct {
	*mock.Call
}

// MkdirAll is a helper method to define mock.On call
//   - path string
func (_e *MockFS_Expecter) MkdirAll(path any) *MockFS_MkdirAll_Call {
	return &MockFS_MkdirAll_Call{Call: _e.mock.On("MkdirAll", path)}
}

func (_c *MockFS_MkdirAll_Call) Run(run func(path string)) *MockFS_MkdirAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFS_MkdirAll_Call) Return(err error) *MockFS_MkdirAll_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFS_MkdirAll_Call) RunAndReturn(run func(path string) error) *MockFS_MkdirAll_Call {
	_c.Call.Return(run)
	return _c
}

// ReadFile provides a mock function for the type MockFS
func (_mock *MockFS) ReadFile(path string) ([]byte, error) {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for ReadFile")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]byte, error)); ok {
		return returnFunc(path)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = returnFunc(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFS_ReadFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadFile'
type MockFS_ReadFile_Call struct {
	*mock.Call
}

// ReadFile is a helper method to define mock.On call
//   - path string
func (_e *MockFS_Expecter) ReadFile(path any) *MockFS_ReadFile_Call {
	return &MockFS_ReadFile_Call{Call: _e.mock.On("ReadFile", path)}
}

func (_c *MockFS_ReadFile_Call) Run(run func(path string)) *MockFS_ReadFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFS_ReadFile_Call) Return(bytes []byte, err error) *MockFS_ReadFile_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockFS_ReadFile_Call) RunAndReturn(run func(path string) ([]byte, error)) *MockFS_ReadFile_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function for the type MockFS
func (_mock *MockFS) Remove(path string) error {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(path)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFS_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type MockFS_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - path string
func (_e *MockFS_Expecter) Remove(path any) *MockFS_Remove_Call {
	return &MockFS_Remove_Call{Call: _e.mock.On("Remove", path)}
}

func (_c *MockFS_Remove_Call) Run(run func(path string)) *MockFS_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFS_Remove_Call) Return(err error) *MockFS_Remove_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFS_Remove_Call) RunAndReturn(run func(path string) error) *MockFS_Remove_Call {
	_c.Call.Return(run)
	return _c
}

// Rename provides a mock function for the type MockFS
func (_mock *MockFS) Rename(old string, new string) error {
	ret := _mock.Called(old, new)

	if len(ret) == 0 {
		panic("no return value specified for Rename")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(old, new)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFS_Rename_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rename'
type MockFS_Rename_Call struct {
	*mock.Call
}

// Rename is a helper method to define mock.On call
//   - old string
//   - new string
func (_e *MockFS_Expecter) Rename(old any, new any) *MockFS_Rename_Call {
	return &MockFS_Rename_Call{Call: _e.mock.On("Rename", old, new)}
}

func (_c *MockFS_Rename_Call) Run(run func(old string, new string)) *MockFS_Rename_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFS_Rename_Call) Return(err error) *MockFS_Rename_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFS_Rename_Call) RunAndReturn(run func(old string, new string) error) *MockFS_Rename_Call {
	_c.Call.Return(run)
	return _c
}

// Symlink provides a mock function for the type MockFS
func (_mock *MockFS) Symlink(target string, link string) error {
	ret := _mock.Called(target, link)

	if len(ret) == 0 {
		panic("no return value specified for Symlink")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(target, link)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFS_Symlink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Symlink'
type MockFS_Symlink_Call struct {
	*mock.Call
}

// Symlink is a helper method to define mock.On call
//   - target string
//   - link string
func (_e *MockFS_Expecter) Symlink(target any, link any) *MockFS_Symlink_Call {
	return &MockFS_Symlink_Call{Call: _e.mock.On("Symlink", target, link)}
}

func (_c *MockFS_Symlink_Call) Run(run func(target string, link string)) *MockFS_Symlink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFS_Symlink_Call) Return(err error) *MockFS_Symlink_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFS_Symlink_Call) RunAndReturn(run func(target string, link string) error) *MockFS_Symlink_Call {
	_c.Call.Return(run)
	return _c
}

// WriteExecutable provides a mock function for the type MockFS
func (_mock *MockFS) WriteExecutable(path string, data []byte) error {
	ret := _mock.Called(path, data)

	if len(ret) == 0 {
		panic("no return value specified for WriteExecutable")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, []byte) error); ok {
		r0 = returnFunc(path, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFS_WriteExecutable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteExecutable'
type MockFS_WriteExecutable_Call struct {
	*mock.Call
}

// WriteExecutable is a helper method to define mock.On call
//   - path string
//   - data []byte
func (_e *MockFS_Expecter) WriteExecutable(path any, data any) *MockFS_WriteExecutable_Call {
	return &MockFS_WriteExecutable_Call{Call: _e.mock.On("WriteExecutable", path, data)}
}

func (_c *MockFS_WriteExecutable_Call) Run(run func(path string, data []byte)) *MockFS_WriteExecutable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFS_WriteExecutable_Call) Return(err error) *MockFS_WriteExecutable_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFS_WriteExecutable_Call) RunAndReturn(run func(path string, data []byte) error) *MockFS_WriteExecutable_Call {
	_c.Call.Return(run)
	return _c
}

// WriteFile provides a mock function for the type MockFS
func (_mock *MockFS) WriteFile(path string, data []byte) error {
	ret := _mock.Called(path, data)

	if len(ret) == 0 {
		panic("no return value specified for WriteFile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, []byte) error); ok {
		r0 = returnFunc(path, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFS_WriteFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteFile'
type MockFS_WriteFile_Call struct {
	*mock.Call
}

// WriteFile is a helper method to define mock.On call
//   - path string
//   - data []byte
func (_e *MockFS_Expecter) WriteFile(path any, data any) *MockFS_WriteFile_Call {
	return &MockFS_WriteFile_Call{Call: _e.mock.On("WriteFile", path, data)}
}

func (_c *MockFS_WriteFile_Call) Run(run func(path string, data []byte)) *MockFS_WriteFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFS_WriteFile_Call) Return(err error) *MockFS_WriteFile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFS_WriteFile_Call) RunAndReturn(run func(path string, data []byte) error) *MockFS_WriteFile_Call {
	_c.Call.Return(run)
	return _c
}
