package rendercontroller

import (
	"errors"
	"fmt"
	"path/filepath"
	"sort"
	"strings"

	"github.com/alexandremahdhaoui/forge-factory/internal/types/rendertypes"
)

const (
	header = "# Generated by forge-factory. DO NOT EDIT. Source: forge-factory.yaml\n"

	// go.mod and go.work take // comments. A # line is an unknown directive and
	// every go command refuses the file outright.
	goHeader = "// Generated by forge-factory. DO NOT EDIT. Source: forge-factory.yaml\n"
)

const defaultGoVersion = "1.25"

var ErrIdentity = errors.New("a repo is missing an identity key its language needs")

// Renderer turns a resolved workspace into the files one language needs.
// Each language engine wires exactly one.
type Renderer interface {
	Language() string
	Render(rendertypes.Input) (rendertypes.Output, error)
}

// reposFor returns the members that speak a language, in declaration order so
// generated files are stable.
func reposFor(in rendertypes.Input, language string) []rendertypes.Repo {
	out := make([]rendertypes.Repo, 0, len(in.Repos))

	for _, r := range in.Repos {
		if r.Speaks(language) {
			out = append(out, r)
		}
	}

	return out
}

// The three things a repo can say about its manifest in the factory block of
// its own forge.yaml. There is no fourth, unwritten one: an absent key means
// committed, the same as writing it.
//
// It used to mean a mode with no name - sync wrote the manifest AND gitignored
// it - which nobody could refer to and which three repos were in by accident
// while git tracked their files anyway. A gitignored file that git already
// tracks is a landmine: the ignore does not apply, so the next version bump
// dirties the tree, the revision comes out -dirty and the release refuses it.
const (
	// OwnManifest: the repo keeps its own manifest and sync writes none.
	// Membership is still generated for it. A pyproject.toml carries pytest,
	// ruff and coverage settings that no factory declares, so taking it over
	// would throw them away.
	OwnManifest = "own"

	// CommittedManifest: sync writes the manifest and the repo commits it, so
	// a bare `go run module@version` works with no workspace. The file is not
	// gitignored, which is the point. This is the default.
	CommittedManifest = "committed"

	// GeneratedManifest: sync writes the manifest and gitignores it. Nobody
	// commits it and nothing outside a synced workspace can build the repo.
	GeneratedManifest = "generated"
)

func ownsItsManifest(repo rendertypes.Repo) bool {
	return repo.Identity["manifest"] == OwnManifest
}

// commitsItsManifest is true unless the repo asked for one of the other two
// modes by name. Committed is the default because the alternative default
// wrote a file and hid it, which reads as "this repo has no manifest" to
// everything that is not a synced workspace.
func commitsItsManifest(repo rendertypes.Repo) bool {
	switch repo.Identity["manifest"] {
	case OwnManifest, GeneratedManifest:
		return false
	default:
		return true
	}
}

func identity(repo rendertypes.Repo, key string) (string, error) {
	value, ok := repo.Identity[key]
	if !ok || strings.TrimSpace(value) == "" {
		return "", fmt.Errorf("%w: %s needs factory.%s in its forge.yaml", ErrIdentity, repo.Name, key)
	}

	return value, nil
}

func sortedNames(deps map[string]string) []string {
	out := make([]string, 0, len(deps))
	for name := range deps {
		out = append(out, name)
	}

	sort.Strings(out)

	return out
}

// Go renders go.mod for every Go member and one go.work at the root.
type Go struct{}

var _ Renderer = Go{}

func (Go) Language() string { return "go" }

func (g Go) Render(in rendertypes.Input) (rendertypes.Output, error) {
	repos := reposFor(in, g.Language())
	if len(repos) == 0 {
		return rendertypes.Output{}, nil
	}

	files := make([]rendertypes.File, 0, len(repos)+1)

	for _, r := range repos {
		if ownsItsManifest(r) {
			continue
		}

		module, err := identity(r, "module")
		if err != nil {
			return rendertypes.Output{}, err
		}

		goVersion := orDefault(r.Identity["goVersion"], defaultGoVersion)

		var b strings.Builder

		fmt.Fprintf(&b, "%s\nmodule %s\n\ngo %s\n", goHeader, module, goVersion)

		// A module never requires itself. Member modules now reach the
		// dependency map so a shared spec is pinned by the register, and a
		// spec's own manifest would otherwise name its own module path.
		requires := make([]string, 0, len(in.Dependencies))

		for _, name := range sortedNames(in.Dependencies) {
			if name != module {
				requires = append(requires, name)
			}
		}

		if len(requires) > 0 {
			fmt.Fprintf(&b, "\nrequire (\n")

			for _, name := range requires {
				fmt.Fprintf(&b, "\t%s %s\n", name, in.Dependencies[name])
			}

			fmt.Fprintf(&b, ")\n")
		}

		file := rendertypes.File{
			Path:       filepath.Join(r.Path, "go.mod"),
			Content:    b.String(),
			Gitignore:  r.Name,
			AlsoIgnore: []string{"go.sum"},
		}

		if commitsItsManifest(r) {
			file.Gitignore = ""
			file.AlsoIgnore = nil
		}

		files = append(files, file)
	}

	var work strings.Builder

	fmt.Fprintf(&work, "%s\ngo %s\n\nuse (\n", goHeader, workVersion(repos))

	for _, r := range repos {
		fmt.Fprintf(&work, "\t./%s\n", r.Name)
	}

	fmt.Fprintf(&work, ")\n")

	files = append(files, rendertypes.File{
		Path:    filepath.Join(in.Root, "go.work"),
		Content: work.String(),
	})

	return rendertypes.Output{Files: files, DependencyLock: dependencyLock(in.Root, repos)}, nil
}

// dependencyLock is what turns the direct requires the factory declares into
// manifests a build can use. Without it the indirect requires and every sum
// are missing. Only this engine knows the commands; who runs them is the
// caller's business.
//
// GOWORK=off matters: in workspace mode a lock writes no per module sums, so
// a member would carry a go.mod naming versions and no go.sum proving them.
// The workspace is synced afterwards, once every member's lock is resolved.
//
// Both are optional because they need the network and a sync must work offline.
func dependencyLock(root string, repos []rendertypes.Repo) []rendertypes.Command {
	out := make([]rendertypes.Command, 0, len(repos)+1)

	for _, r := range repos {
		if ownsItsManifest(r) {
			continue
		}

		out = append(out, rendertypes.Command{
			Dir:      r.Path,
			Command:  "go",
			Args:     []string{"mod", "tidy"},
			Env:      map[string]string{"GOWORK": "off"},
			Optional: true,
		})
	}

	// GOWORK is named rather than inherited. A caller running with GOWORK=off
	// makes go work sync report that no go.work exists, one line after this
	// same sync wrote it.
	return append(out, rendertypes.Command{
		Dir:      root,
		Command:  "go",
		Args:     []string{"work", "sync"},
		Env:      map[string]string{"GOWORK": filepath.Join(root, "go.work")},
		Optional: true,
	})
}

// workVersion picks the newest go a member asks for. A go.work older than any
// member refuses to load the whole workspace.
func workVersion(repos []rendertypes.Repo) string {
	best := defaultGoVersion

	for _, r := range repos {
		if newerGo(r.Identity["goVersion"], best) {
			best = r.Identity["goVersion"]
		}
	}

	return best
}

func newerGo(candidate, best string) bool {
	if candidate == "" {
		return false
	}

	a := versionParts(candidate)
	b := versionParts(best)

	for i := range a {
		if i >= len(b) {
			return true
		}

		if a[i] != b[i] {
			return a[i] > b[i]
		}
	}

	return false
}

func versionParts(v string) []int {
	fields := strings.Split(v, ".")
	out := make([]int, 0, len(fields))

	for _, f := range fields {
		n := 0

		for _, r := range f {
			if r < '0' || r > '9' {
				n = -1

				break
			}

			n = n*10 + int(r-'0')
		}

		out = append(out, n)
	}

	return out
}

// Rust renders one root Cargo.toml. Cargo already centralises versions, and
// member crates carry no version at all, so nothing is written inside a repo.
type Rust struct{}

var _ Renderer = Rust{}

func (Rust) Language() string { return "rust" }

func (r Rust) Render(in rendertypes.Input) (rendertypes.Output, error) {
	repos := reposFor(in, r.Language())
	if len(repos) == 0 {
		return rendertypes.Output{}, nil
	}

	var b strings.Builder

	fmt.Fprintf(&b, "%s\n[workspace]\nresolver = \"2\"\nmembers = [\n", header)

	for _, repo := range repos {
		fmt.Fprintf(&b, "    %q,\n", repo.Name)

		for _, extra := range strings.Split(repo.Identity["cargoMembers"], ",") {
			if trimmed := strings.TrimSpace(extra); trimmed != "" {
				fmt.Fprintf(&b, "    %q,\n", trimmed)
			}
		}
	}

	fmt.Fprintf(&b, "]\n")

	if names := sortedNames(in.Dependencies); len(names) > 0 {
		fmt.Fprintf(&b, "\n[workspace.dependencies]\n")

		for _, name := range names {
			fmt.Fprintf(&b, "%s = %s\n", name, tomlValue(in.Dependencies[name]))
		}
	}

	return rendertypes.Output{Files: []rendertypes.File{{
		Path:    filepath.Join(in.Root, "Cargo.toml"),
		Content: b.String(),
	}}}, nil
}

// tomlValue takes a version verbatim when it is already TOML, and quotes it
// otherwise. A bare 1 is not a cargo version, and a dependency that needs
// features is written as a whole inline table in the factory.
func tomlValue(v string) string {
	switch {
	case v == "":
		return `""`
	case strings.HasPrefix(v, "{"), strings.HasPrefix(v, "["), strings.HasPrefix(v, `"`):
		return v
	default:
		return `"` + v + `"`
	}
}

// Python renders pyproject.toml for every Python member, whole, because the
// file holds build and tool configuration alongside dependencies.
type Python struct{}

var _ Renderer = Python{}

func (Python) Language() string { return "python" }

func (p Python) Render(in rendertypes.Input) (rendertypes.Output, error) {
	repos := reposFor(in, p.Language())
	files := make([]rendertypes.File, 0, len(repos))

	for _, r := range repos {
		if ownsItsManifest(r) {
			continue
		}

		pkg, err := identity(r, "package")
		if err != nil {
			return rendertypes.Output{}, err
		}

		var b strings.Builder

		fmt.Fprintf(&b, "%s\n[project]\nname = %q\nversion = %q\n",
			header, r.Name, orDefault(r.Identity["version"], "0.1.0"))

		if desc := r.Identity["description"]; desc != "" {
			fmt.Fprintf(&b, "description = %q\n", desc)
		}

		fmt.Fprintf(&b, "requires-python = %q\n", orDefault(r.Identity["requiresPython"], ">=3.12"))
		writeRequirements(&b, "dependencies", in.Dependencies)

		if entry := r.Identity["entrypoint"]; entry != "" {
			fmt.Fprintf(&b, "\n[project.scripts]\n%s = %q\n", r.Name, entry)
		}

		if len(in.Dev) > 0 {
			b.WriteString("\n[dependency-groups]\n")
			writeRequirements(&b, "dev", in.Dev)
		}

		fmt.Fprintf(&b, "\n[build-system]\nrequires = [\"hatchling\"]\n")
		fmt.Fprintf(&b, "build-backend = \"hatchling.build\"\n\n")
		fmt.Fprintf(&b, "[tool.hatch.build.targets.wheel]\npackages = [\"src/%s\"]\n", pkg)

		writeToolConfig(&b, r)

		files = append(files, rendertypes.File{
			Path:       filepath.Join(r.Path, "pyproject.toml"),
			Content:    b.String(),
			Gitignore:  r.Name,
			AlsoIgnore: []string{"uv.lock"},
		})
	}

	return rendertypes.Output{Files: files}, nil
}

// writeRequirements writes a PEP 508 list. The version is glued to the name,
// so a pin travels as pytest>=8 and not as two fields.
func writeRequirements(b *strings.Builder, key string, deps map[string]string) {
	fmt.Fprintf(b, "%s = [\n", key)

	for _, name := range sortedNames(deps) {
		fmt.Fprintf(b, "    \"%s%s\",\n", name, deps[name])
	}

	b.WriteString("]\n")
}

// writeToolConfig appends what only the repo knows. pytest options, ruff rules
// and coverage omits are the repo's business and no factory declares them, so
// the repo carries them verbatim in its own forge.yaml.
func writeToolConfig(b *strings.Builder, repo rendertypes.Repo) {
	config := strings.TrimSpace(repo.Identity["toolConfig"])
	if config == "" {
		return
	}

	fmt.Fprintf(b, "\n%s\n", config)
}

// TypeScript renders package.json for every member and one pnpm-workspace.yaml.
// The rendered package.json carries no scripts. They duplicate forge stages.
type TypeScript struct{}

var _ Renderer = TypeScript{}

func (TypeScript) Language() string { return "typescript" }

func (t TypeScript) Render(in rendertypes.Input) (rendertypes.Output, error) {
	repos := reposFor(in, t.Language())
	if len(repos) == 0 {
		return rendertypes.Output{}, nil
	}

	files := make([]rendertypes.File, 0, len(repos)+1)

	for _, r := range repos {
		if ownsItsManifest(r) {
			continue
		}

		files = append(files, rendertypes.File{
			Path:       filepath.Join(r.Path, "package.json"),
			Content:    packageJSON(r, in),
			Gitignore:  r.Name,
			AlsoIgnore: []string{"tsconfig.tsbuildinfo"},
		})
	}

	var ws strings.Builder

	fmt.Fprintf(&ws, "%s\npackages:\n", header)

	for _, r := range repos {
		fmt.Fprintf(&ws, "  - %q\n", r.Name)
	}

	// pnpm blocks a dependency's build script by default. A package that needs
	// its platform binary built has to be named, and the list is per workspace,
	// so members contribute to it.
	if allowed := allowBuilds(repos); len(allowed) > 0 {
		fmt.Fprintf(&ws, "\nallowBuilds:\n")

		for _, name := range allowed {
			fmt.Fprintf(&ws, "  %s: true\n", name)
		}
	}

	files = append(files, rendertypes.File{
		Path:    filepath.Join(in.Root, "pnpm-workspace.yaml"),
		Content: ws.String(),
	})

	return rendertypes.Output{Files: files}, nil
}

// packageJSON writes the whole file. It carries no scripts: they would be a
// second way to run what forge stages already run.
func packageJSON(r rendertypes.Repo, in rendertypes.Input) string {
	var b strings.Builder

	fmt.Fprintf(&b, "{\n  \"_generated\": \"by forge-factory from forge-factory.yaml. DO NOT EDIT.\",\n")
	fmt.Fprintf(&b, "  \"name\": %q,\n  \"version\": %q,\n  \"private\": true,\n  \"type\": \"module\",\n",
		r.Name, orDefault(r.Identity["version"], "0.1.0"))

	if desc := r.Identity["description"]; desc != "" {
		fmt.Fprintf(&b, "  \"description\": %q,\n", desc)
	}

	if bin := r.Identity["bin"]; bin != "" {
		fmt.Fprintf(&b, "  \"bin\": { %q: %q },\n", r.Name, bin)
	}

	writeJSONDeps(&b, "dependencies", in.Dependencies, len(in.Dev) > 0)

	if len(in.Dev) > 0 {
		writeJSONDeps(&b, "devDependencies", in.Dev, false)
	}

	b.WriteString("}\n")

	return b.String()
}

func writeJSONDeps(b *strings.Builder, key string, deps map[string]string, more bool) {
	fmt.Fprintf(b, "  %q: {\n", key)

	names := sortedNames(deps)
	for i, name := range names {
		comma := ","
		if i == len(names)-1 {
			comma = ""
		}

		fmt.Fprintf(b, "    %q: %q%s\n", name, deps[name], comma)
	}

	trailing := ""
	if more {
		trailing = ","
	}

	fmt.Fprintf(b, "  }%s\n", trailing)
}

func allowBuilds(repos []rendertypes.Repo) []string {
	seen := map[string]bool{}

	for _, r := range repos {
		for _, name := range strings.Split(r.Identity["allowBuilds"], ",") {
			if trimmed := strings.TrimSpace(name); trimmed != "" {
				seen[trimmed] = true
			}
		}
	}

	out := make([]string, 0, len(seen))
	for name := range seen {
		out = append(out, name)
	}

	sort.Strings(out)

	return out
}

func orDefault(value, fallback string) string {
	if strings.TrimSpace(value) == "" {
		return fallback
	}

	return value
}
