package rendercontroller

import (
	"errors"
	"fmt"
	"path/filepath"
	"sort"
	"strings"

	"github.com/alexandremahdhaoui/forge-factory/internal/types/rendertypes"
)

const (
	header = "# Generated by forge-factory. DO NOT EDIT. Source: forge-factory.yaml\n"

	// go.mod and go.work take // comments. A # line is an unknown directive and
	// every go command refuses the file outright.
	goHeader = "// Generated by forge-factory. DO NOT EDIT. Source: forge-factory.yaml\n"
)

const defaultGoVersion = "1.25"

var ErrIdentity = errors.New("a repo is missing an identity key its language needs")

// Renderer turns a resolved workspace into the files one language needs.
// Each language engine wires exactly one.
type Renderer interface {
	Language() string
	Render(rendertypes.Input) (rendertypes.Output, error)
}

// reposFor returns the members that speak a language, in declaration order so
// generated files are stable.
func reposFor(in rendertypes.Input, language string) []rendertypes.Repo {
	out := make([]rendertypes.Repo, 0, len(in.Repos))

	for _, r := range in.Repos {
		if r.Speaks(language) {
			out = append(out, r)
		}
	}

	return out
}

func identity(repo rendertypes.Repo, key string) (string, error) {
	value, ok := repo.Identity[key]
	if !ok || strings.TrimSpace(value) == "" {
		return "", fmt.Errorf("%w: %s needs factory.%s in its forge.yaml", ErrIdentity, repo.Name, key)
	}

	return value, nil
}

func sortedNames(deps map[string]string) []string {
	out := make([]string, 0, len(deps))
	for name := range deps {
		out = append(out, name)
	}

	sort.Strings(out)

	return out
}

// Go renders go.mod for every Go member and one go.work at the root.
type Go struct{}

var _ Renderer = Go{}

func (Go) Language() string { return "go" }

func (g Go) Render(in rendertypes.Input) (rendertypes.Output, error) {
	repos := reposFor(in, g.Language())
	if len(repos) == 0 {
		return rendertypes.Output{}, nil
	}

	files := make([]rendertypes.File, 0, len(repos)+1)

	for _, r := range repos {
		module, err := identity(r, "module")
		if err != nil {
			return rendertypes.Output{}, err
		}

		goVersion := orDefault(r.Identity["goVersion"], defaultGoVersion)

		var b strings.Builder

		fmt.Fprintf(&b, "%s\nmodule %s\n\ngo %s\n", goHeader, module, goVersion)

		if names := sortedNames(in.Dependencies); len(names) > 0 {
			fmt.Fprintf(&b, "\nrequire (\n")

			for _, name := range names {
				fmt.Fprintf(&b, "\t%s %s\n", name, in.Dependencies[name])
			}

			fmt.Fprintf(&b, ")\n")
		}

		files = append(files, rendertypes.File{
			Path:       filepath.Join(r.Path, "go.mod"),
			Content:    b.String(),
			Gitignore:  r.Name,
			AlsoIgnore: []string{"go.sum"},
		})
	}

	var work strings.Builder

	fmt.Fprintf(&work, "%s\ngo %s\n\nuse (\n", goHeader, workVersion(repos))

	for _, r := range repos {
		fmt.Fprintf(&work, "\t./%s\n", r.Name)
	}

	fmt.Fprintf(&work, ")\n")

	files = append(files, rendertypes.File{
		Path:    filepath.Join(in.Root, "go.work"),
		Content: work.String(),
	})

	return rendertypes.Output{Files: files, Settle: tidy(in.Root, repos)}, nil
}

// tidy is what turns the direct requires the factory declares into a go.mod a
// build can use. Without it the indirect requires and every sum are missing.
//
// GOWORK=off matters: in workspace mode a tidy writes no per module sums, so a
// member would carry a go.mod naming versions and no go.sum proving them. The
// workspace is synced afterwards, once every member is tidy.
//
// Both are optional because they need the network and a sync must work offline.
func tidy(root string, repos []rendertypes.Repo) []rendertypes.Command {
	out := make([]rendertypes.Command, 0, len(repos)+1)

	for _, r := range repos {
		out = append(out, rendertypes.Command{
			Dir:      r.Path,
			Command:  "go",
			Args:     []string{"mod", "tidy"},
			Env:      map[string]string{"GOWORK": "off"},
			Optional: true,
		})
	}

	return append(out, rendertypes.Command{
		Dir:      root,
		Command:  "go",
		Args:     []string{"work", "sync"},
		Optional: true,
	})
}

// workVersion picks the newest go a member asks for. A go.work older than any
// member refuses to load the whole workspace.
func workVersion(repos []rendertypes.Repo) string {
	best := defaultGoVersion

	for _, r := range repos {
		if newerGo(r.Identity["goVersion"], best) {
			best = r.Identity["goVersion"]
		}
	}

	return best
}

func newerGo(candidate, best string) bool {
	if candidate == "" {
		return false
	}

	a := versionParts(candidate)
	b := versionParts(best)

	for i := range a {
		if i >= len(b) {
			return true
		}

		if a[i] != b[i] {
			return a[i] > b[i]
		}
	}

	return false
}

func versionParts(v string) []int {
	fields := strings.Split(v, ".")
	out := make([]int, 0, len(fields))

	for _, f := range fields {
		n := 0

		for _, r := range f {
			if r < '0' || r > '9' {
				n = -1

				break
			}

			n = n*10 + int(r-'0')
		}

		out = append(out, n)
	}

	return out
}

// Rust renders one root Cargo.toml. Cargo already centralises versions, and
// member crates carry no version at all, so nothing is written inside a repo.
type Rust struct{}

var _ Renderer = Rust{}

func (Rust) Language() string { return "rust" }

func (r Rust) Render(in rendertypes.Input) (rendertypes.Output, error) {
	repos := reposFor(in, r.Language())
	if len(repos) == 0 {
		return rendertypes.Output{}, nil
	}

	var b strings.Builder

	fmt.Fprintf(&b, "%s\n[workspace]\nresolver = \"2\"\nmembers = [\n", header)

	for _, repo := range repos {
		fmt.Fprintf(&b, "    %q,\n", repo.Name)

		for _, extra := range strings.Split(repo.Identity["cargoMembers"], ",") {
			if trimmed := strings.TrimSpace(extra); trimmed != "" {
				fmt.Fprintf(&b, "    %q,\n", trimmed)
			}
		}
	}

	fmt.Fprintf(&b, "]\n")

	if names := sortedNames(in.Dependencies); len(names) > 0 {
		fmt.Fprintf(&b, "\n[workspace.dependencies]\n")

		for _, name := range names {
			fmt.Fprintf(&b, "%s = %s\n", name, in.Dependencies[name])
		}
	}

	return rendertypes.Output{Files: []rendertypes.File{{
		Path:    filepath.Join(in.Root, "Cargo.toml"),
		Content: b.String(),
	}}}, nil
}

// Python renders pyproject.toml for every Python member, whole, because the
// file holds build and tool configuration alongside dependencies.
type Python struct{}

var _ Renderer = Python{}

func (Python) Language() string { return "python" }

func (p Python) Render(in rendertypes.Input) (rendertypes.Output, error) {
	repos := reposFor(in, p.Language())
	files := make([]rendertypes.File, 0, len(repos))

	for _, r := range repos {
		pkg, err := identity(r, "package")
		if err != nil {
			return rendertypes.Output{}, err
		}

		var b strings.Builder

		fmt.Fprintf(&b, "%s\n[project]\nname = %q\nversion = %q\n",
			header, r.Name, orDefault(r.Identity["version"], "0.1.0"))
		fmt.Fprintf(&b, "requires-python = %q\n", orDefault(r.Identity["requiresPython"], ">=3.12"))
		fmt.Fprintf(&b, "dependencies = [\n")

		for _, name := range sortedNames(in.Dependencies) {
			fmt.Fprintf(&b, "    \"%s%s\",\n", name, in.Dependencies[name])
		}

		fmt.Fprintf(&b, "]\n\n[build-system]\nrequires = [\"hatchling\"]\n")
		fmt.Fprintf(&b, "build-backend = \"hatchling.build\"\n\n")
		fmt.Fprintf(&b, "[tool.hatch.build.targets.wheel]\npackages = [\"src/%s\"]\n", pkg)

		files = append(files, rendertypes.File{
			Path:      filepath.Join(r.Path, "pyproject.toml"),
			Content:   b.String(),
			Gitignore: r.Name,
		})
	}

	return rendertypes.Output{Files: files}, nil
}

// TypeScript renders package.json for every member and one pnpm-workspace.yaml.
// The rendered package.json carries no scripts. They duplicate forge stages.
type TypeScript struct{}

var _ Renderer = TypeScript{}

func (TypeScript) Language() string { return "typescript" }

func (t TypeScript) Render(in rendertypes.Input) (rendertypes.Output, error) {
	repos := reposFor(in, t.Language())
	if len(repos) == 0 {
		return rendertypes.Output{}, nil
	}

	files := make([]rendertypes.File, 0, len(repos)+1)

	for _, r := range repos {
		var b strings.Builder

		fmt.Fprintf(&b, "{\n  \"_generated\": \"by forge-factory from forge-factory.yaml. DO NOT EDIT.\",\n")
		fmt.Fprintf(&b, "  \"name\": %q,\n  \"version\": %q,\n  \"private\": true,\n  \"type\": \"module\",\n",
			r.Name, orDefault(r.Identity["version"], "0.1.0"))

		if bin := r.Identity["bin"]; bin != "" {
			fmt.Fprintf(&b, "  \"bin\": { %q: %q },\n", r.Name, bin)
		}

		fmt.Fprintf(&b, "  \"dependencies\": {\n")

		names := sortedNames(in.Dependencies)
		for i, name := range names {
			comma := ","
			if i == len(names)-1 {
				comma = ""
			}

			fmt.Fprintf(&b, "    %q: %q%s\n", name, in.Dependencies[name], comma)
		}

		fmt.Fprintf(&b, "  }\n}\n")

		files = append(files, rendertypes.File{
			Path:      filepath.Join(r.Path, "package.json"),
			Content:   b.String(),
			Gitignore: r.Name,
		})
	}

	var ws strings.Builder

	fmt.Fprintf(&ws, "%s\npackages:\n", header)

	for _, r := range repos {
		fmt.Fprintf(&ws, "  - %q\n", r.Name)
	}

	files = append(files, rendertypes.File{
		Path:    filepath.Join(in.Root, "pnpm-workspace.yaml"),
		Content: ws.String(),
	})

	return rendertypes.Output{Files: files}, nil
}

func orDefault(value, fallback string) string {
	if strings.TrimSpace(value) == "" {
		return fallback
	}

	return value
}
