// Code generated by forge-dev. DO NOT EDIT.
// Source: spec.openapi.yaml
// SourceChecksum: sha256:8c3473067a76a1acb639f7089c6f241339387b7848dc816918f49ebbe03c1953

package main

import (
	"fmt"

	"github.com/alexandremahdhaoui/forge/pkg/mcptypes"
)

// ValidateCommand validates a Command and returns validation results.
// It checks required fields and validates enum values.
func ValidateCommand(s *Command) *mcptypes.ConfigValidateOutput {
	if s == nil {
		return &mcptypes.ConfigValidateOutput{
			Valid: true,
		}
	}

	var errors []mcptypes.ValidationError
	// Validate required field: command
	if s.Command == "" {
		errors = append(errors, mcptypes.ValidationError{
			Field:   "spec.command",
			Message: "required field is missing",
		})
	}
	// Validate required field: dir
	if s.Dir == "" {
		errors = append(errors, mcptypes.ValidationError{
			Field:   "spec.dir",
			Message: "required field is missing",
		})
	}

	if len(errors) > 0 {
		return &mcptypes.ConfigValidateOutput{
			Valid:  false,
			Errors: errors,
		}
	}

	return &mcptypes.ConfigValidateOutput{
		Valid: true,
	}
}

// ValidateSpec validates a Spec and returns validation results.
// It checks required fields and validates enum values.
func ValidateSpec(s *Spec) *mcptypes.ConfigValidateOutput {
	if s == nil {
		return &mcptypes.ConfigValidateOutput{
			Valid: true,
		}
	}

	var errors []mcptypes.ValidationError

	if len(errors) > 0 {
		return &mcptypes.ConfigValidateOutput{
			Valid:  false,
			Errors: errors,
		}
	}

	return &mcptypes.ConfigValidateOutput{
		Valid: true,
	}
}

// ValidateRuntimePick validates a RuntimePick and returns validation results.
// It checks required fields and validates enum values.
func ValidateRuntimePick(s *RuntimePick) *mcptypes.ConfigValidateOutput {
	if s == nil {
		return &mcptypes.ConfigValidateOutput{
			Valid: true,
		}
	}

	var errors []mcptypes.ValidationError

	if len(errors) > 0 {
		return &mcptypes.ConfigValidateOutput{
			Valid:  false,
			Errors: errors,
		}
	}

	return &mcptypes.ConfigValidateOutput{
		Valid: true,
	}
}

// ValidateFetchOutput validates a FetchOutput and returns validation results.
// It checks required fields and validates enum values.
func ValidateFetchOutput(s *FetchOutput) *mcptypes.ConfigValidateOutput {
	if s == nil {
		return &mcptypes.ConfigValidateOutput{
			Valid: true,
		}
	}

	var errors []mcptypes.ValidationError
	// Validate required field: path
	if s.Path == "" {
		errors = append(errors, mcptypes.ValidationError{
			Field:   "spec.path",
			Message: "required field is missing",
		})
	}
	// Validate required field: sha256
	if s.Sha256 == "" {
		errors = append(errors, mcptypes.ValidationError{
			Field:   "spec.sha256",
			Message: "required field is missing",
		})
	}

	if len(errors) > 0 {
		return &mcptypes.ConfigValidateOutput{
			Valid:  false,
			Errors: errors,
		}
	}

	return &mcptypes.ConfigValidateOutput{
		Valid: true,
	}
}

// ValidateFile validates a File and returns validation results.
// It checks required fields and validates enum values.
func ValidateFile(s *File) *mcptypes.ConfigValidateOutput {
	if s == nil {
		return &mcptypes.ConfigValidateOutput{
			Valid: true,
		}
	}

	var errors []mcptypes.ValidationError
	// Validate required field: content
	if s.Content == "" {
		errors = append(errors, mcptypes.ValidationError{
			Field:   "spec.content",
			Message: "required field is missing",
		})
	}
	// Validate required field: path
	if s.Path == "" {
		errors = append(errors, mcptypes.ValidationError{
			Field:   "spec.path",
			Message: "required field is missing",
		})
	}

	if len(errors) > 0 {
		return &mcptypes.ConfigValidateOutput{
			Valid:  false,
			Errors: errors,
		}
	}

	return &mcptypes.ConfigValidateOutput{
		Valid: true,
	}
}

// ValidateInstallOutput validates a InstallOutput and returns validation results.
// It checks required fields and validates enum values.
func ValidateInstallOutput(s *InstallOutput) *mcptypes.ConfigValidateOutput {
	if s == nil {
		return &mcptypes.ConfigValidateOutput{
			Valid: true,
		}
	}

	var errors []mcptypes.ValidationError
	// Validate required field: installed
	if len(s.Installed) == 0 {
		errors = append(errors, mcptypes.ValidationError{
			Field:   "spec.installed",
			Message: "required field is missing or empty",
		})
	}

	if len(errors) > 0 {
		return &mcptypes.ConfigValidateOutput{
			Valid:  false,
			Errors: errors,
		}
	}

	return &mcptypes.ConfigValidateOutput{
		Valid: true,
	}
}

// ValidateLanguageOutput validates a LanguageOutput and returns validation results.
// It checks required fields and validates enum values.
func ValidateLanguageOutput(s *LanguageOutput) *mcptypes.ConfigValidateOutput {
	if s == nil {
		return &mcptypes.ConfigValidateOutput{
			Valid: true,
		}
	}

	var errors []mcptypes.ValidationError
	// Validate required field: language
	if s.Language == "" {
		errors = append(errors, mcptypes.ValidationError{
			Field:   "spec.language",
			Message: "required field is missing",
		})
	}

	if len(errors) > 0 {
		return &mcptypes.ConfigValidateOutput{
			Valid:  false,
			Errors: errors,
		}
	}

	return &mcptypes.ConfigValidateOutput{
		Valid: true,
	}
}

// ValidateRepo validates a Repo and returns validation results.
// It checks required fields and validates enum values.
func ValidateRepo(s *Repo) *mcptypes.ConfigValidateOutput {
	if s == nil {
		return &mcptypes.ConfigValidateOutput{
			Valid: true,
		}
	}

	var errors []mcptypes.ValidationError
	// Validate required field: name
	if s.Name == "" {
		errors = append(errors, mcptypes.ValidationError{
			Field:   "spec.name",
			Message: "required field is missing",
		})
	}
	// Validate required field: path
	if s.Path == "" {
		errors = append(errors, mcptypes.ValidationError{
			Field:   "spec.path",
			Message: "required field is missing",
		})
	}

	if len(errors) > 0 {
		return &mcptypes.ConfigValidateOutput{
			Valid:  false,
			Errors: errors,
		}
	}

	return &mcptypes.ConfigValidateOutput{
		Valid: true,
	}
}

// ValidateRuntimePrerequisite validates a RuntimePrerequisite and returns validation results.
// It checks required fields and validates enum values.
func ValidateRuntimePrerequisite(s *RuntimePrerequisite) *mcptypes.ConfigValidateOutput {
	if s == nil {
		return &mcptypes.ConfigValidateOutput{
			Valid: true,
		}
	}

	var errors []mcptypes.ValidationError
	// Validate required field: name
	if s.Name == "" {
		errors = append(errors, mcptypes.ValidationError{
			Field:   "spec.name",
			Message: "required field is missing",
		})
	}
	// Validate required field: reason
	if s.Reason == "" {
		errors = append(errors, mcptypes.ValidationError{
			Field:   "spec.reason",
			Message: "required field is missing",
		})
	}

	if len(errors) > 0 {
		return &mcptypes.ConfigValidateOutput{
			Valid:  false,
			Errors: errors,
		}
	}

	return &mcptypes.ConfigValidateOutput{
		Valid: true,
	}
}

// ValidateDescribeInput validates a DescribeInput and returns validation results.
// It checks required fields and validates enum values.
func ValidateDescribeInput(s *DescribeInput) *mcptypes.ConfigValidateOutput {
	if s == nil {
		return &mcptypes.ConfigValidateOutput{
			Valid: true,
		}
	}

	var errors []mcptypes.ValidationError
	// Validate required field: arch
	if s.Arch == "" {
		errors = append(errors, mcptypes.ValidationError{
			Field:   "spec.arch",
			Message: "required field is missing",
		})
	}
	// Validate required field: os
	if s.Os == "" {
		errors = append(errors, mcptypes.ValidationError{
			Field:   "spec.os",
			Message: "required field is missing",
		})
	}
	// Validate required field: runtime
	if s.Runtime == "" {
		errors = append(errors, mcptypes.ValidationError{
			Field:   "spec.runtime",
			Message: "required field is missing",
		})
	}
	// Validate nested reference: spec
	{
		nested := s.Spec
		nestedResult := ValidateSpec(&nested)
		if !nestedResult.Valid {
			for _, e := range nestedResult.Errors {
				errors = append(errors, mcptypes.ValidationError{
					Field:   "spec.spec." + e.Field,
					Message: e.Message,
				})
			}
		}
	}
	// Validate required field: version
	if s.Version == "" {
		errors = append(errors, mcptypes.ValidationError{
			Field:   "spec.version",
			Message: "required field is missing",
		})
	}

	if len(errors) > 0 {
		return &mcptypes.ConfigValidateOutput{
			Valid:  false,
			Errors: errors,
		}
	}

	return &mcptypes.ConfigValidateOutput{
		Valid: true,
	}
}

// ValidateRuntimeArtifact validates a RuntimeArtifact and returns validation results.
// It checks required fields and validates enum values.
func ValidateRuntimeArtifact(s *RuntimeArtifact) *mcptypes.ConfigValidateOutput {
	if s == nil {
		return &mcptypes.ConfigValidateOutput{
			Valid: true,
		}
	}

	var errors []mcptypes.ValidationError
	// Validate array of references: picks
	for i, item := range s.Picks {
		nestedResult := ValidateRuntimePick(&item)
		if !nestedResult.Valid {
			for _, e := range nestedResult.Errors {
				errors = append(errors, mcptypes.ValidationError{
					Field:   fmt.Sprintf("spec.picks[%d].%s", i, e.Field),
					Message: e.Message,
				})
			}
		}
	}
	// Validate required field: sha256
	if s.Sha256 == "" {
		errors = append(errors, mcptypes.ValidationError{
			Field:   "spec.sha256",
			Message: "required field is missing",
		})
	}
	// Validate required field: unpack
	if s.Unpack == "" {
		errors = append(errors, mcptypes.ValidationError{
			Field:   "spec.unpack",
			Message: "required field is missing",
		})
	}
	// Validate enum field: unpack
	if s.Unpack != "" {
		validValues := []string{"file", "tar", "tar-gz", "zip"}
		valid := false
		for _, v := range validValues {
			if s.Unpack == v {
				valid = true
				break
			}
		}
		if !valid {
			errors = append(errors, mcptypes.ValidationError{
				Field:   "spec.unpack",
				Message: "must be one of: file, tar, tar-gz, zip",
			})
		}
	}
	// Validate required field: url
	if s.Url == "" {
		errors = append(errors, mcptypes.ValidationError{
			Field:   "spec.url",
			Message: "required field is missing",
		})
	}

	if len(errors) > 0 {
		return &mcptypes.ConfigValidateOutput{
			Valid:  false,
			Errors: errors,
		}
	}

	return &mcptypes.ConfigValidateOutput{
		Valid: true,
	}
}

// ValidateRenderOutput validates a RenderOutput and returns validation results.
// It checks required fields and validates enum values.
func ValidateRenderOutput(s *RenderOutput) *mcptypes.ConfigValidateOutput {
	if s == nil {
		return &mcptypes.ConfigValidateOutput{
			Valid: true,
		}
	}

	var errors []mcptypes.ValidationError
	// Validate array of references: dependencyLock
	for i, item := range s.DependencyLock {
		nestedResult := ValidateCommand(&item)
		if !nestedResult.Valid {
			for _, e := range nestedResult.Errors {
				errors = append(errors, mcptypes.ValidationError{
					Field:   fmt.Sprintf("spec.dependencyLock[%d].%s", i, e.Field),
					Message: e.Message,
				})
			}
		}
	}
	// Validate required array of references: files
	if len(s.Files) == 0 {
		errors = append(errors, mcptypes.ValidationError{
			Field:   "spec.files",
			Message: "required field is missing or empty",
		})
	}
	// Validate array of references: files
	for i, item := range s.Files {
		nestedResult := ValidateFile(&item)
		if !nestedResult.Valid {
			for _, e := range nestedResult.Errors {
				errors = append(errors, mcptypes.ValidationError{
					Field:   fmt.Sprintf("spec.files[%d].%s", i, e.Field),
					Message: e.Message,
				})
			}
		}
	}

	if len(errors) > 0 {
		return &mcptypes.ConfigValidateOutput{
			Valid:  false,
			Errors: errors,
		}
	}

	return &mcptypes.ConfigValidateOutput{
		Valid: true,
	}
}

// ValidateRenderInput validates a RenderInput and returns validation results.
// It checks required fields and validates enum values.
func ValidateRenderInput(s *RenderInput) *mcptypes.ConfigValidateOutput {
	if s == nil {
		return &mcptypes.ConfigValidateOutput{
			Valid: true,
		}
	}

	var errors []mcptypes.ValidationError
	// Validate required array of references: repos
	if len(s.Repos) == 0 {
		errors = append(errors, mcptypes.ValidationError{
			Field:   "spec.repos",
			Message: "required field is missing or empty",
		})
	}
	// Validate array of references: repos
	for i, item := range s.Repos {
		nestedResult := ValidateRepo(&item)
		if !nestedResult.Valid {
			for _, e := range nestedResult.Errors {
				errors = append(errors, mcptypes.ValidationError{
					Field:   fmt.Sprintf("spec.repos[%d].%s", i, e.Field),
					Message: e.Message,
				})
			}
		}
	}
	// Validate required field: root
	if s.Root == "" {
		errors = append(errors, mcptypes.ValidationError{
			Field:   "spec.root",
			Message: "required field is missing",
		})
	}
	// Validate nested reference: spec
	{
		nested := s.Spec
		nestedResult := ValidateSpec(&nested)
		if !nestedResult.Valid {
			for _, e := range nestedResult.Errors {
				errors = append(errors, mcptypes.ValidationError{
					Field:   "spec.spec." + e.Field,
					Message: e.Message,
				})
			}
		}
	}

	if len(errors) > 0 {
		return &mcptypes.ConfigValidateOutput{
			Valid:  false,
			Errors: errors,
		}
	}

	return &mcptypes.ConfigValidateOutput{
		Valid: true,
	}
}

// ValidateFetchInput validates a FetchInput and returns validation results.
// It checks required fields and validates enum values.
func ValidateFetchInput(s *FetchInput) *mcptypes.ConfigValidateOutput {
	if s == nil {
		return &mcptypes.ConfigValidateOutput{
			Valid: true,
		}
	}

	var errors []mcptypes.ValidationError
	// Validate required reference field: artifact
	// Validate nested reference: artifact
	{
		nested := s.Artifact
		nestedResult := ValidateRuntimeArtifact(&nested)
		if !nestedResult.Valid {
			for _, e := range nestedResult.Errors {
				errors = append(errors, mcptypes.ValidationError{
					Field:   "spec.artifact." + e.Field,
					Message: e.Message,
				})
			}
		}
	}
	// Validate required field: dest
	if s.Dest == "" {
		errors = append(errors, mcptypes.ValidationError{
			Field:   "spec.dest",
			Message: "required field is missing",
		})
	}
	// Validate nested reference: spec
	{
		nested := s.Spec
		nestedResult := ValidateSpec(&nested)
		if !nestedResult.Valid {
			for _, e := range nestedResult.Errors {
				errors = append(errors, mcptypes.ValidationError{
					Field:   "spec.spec." + e.Field,
					Message: e.Message,
				})
			}
		}
	}

	if len(errors) > 0 {
		return &mcptypes.ConfigValidateOutput{
			Valid:  false,
			Errors: errors,
		}
	}

	return &mcptypes.ConfigValidateOutput{
		Valid: true,
	}
}

// ValidateFetchedArchive validates a FetchedArchive and returns validation results.
// It checks required fields and validates enum values.
func ValidateFetchedArchive(s *FetchedArchive) *mcptypes.ConfigValidateOutput {
	if s == nil {
		return &mcptypes.ConfigValidateOutput{
			Valid: true,
		}
	}

	var errors []mcptypes.ValidationError
	// Validate required reference field: artifact
	// Validate nested reference: artifact
	{
		nested := s.Artifact
		nestedResult := ValidateRuntimeArtifact(&nested)
		if !nestedResult.Valid {
			for _, e := range nestedResult.Errors {
				errors = append(errors, mcptypes.ValidationError{
					Field:   "spec.artifact." + e.Field,
					Message: e.Message,
				})
			}
		}
	}
	// Validate required field: path
	if s.Path == "" {
		errors = append(errors, mcptypes.ValidationError{
			Field:   "spec.path",
			Message: "required field is missing",
		})
	}

	if len(errors) > 0 {
		return &mcptypes.ConfigValidateOutput{
			Valid:  false,
			Errors: errors,
		}
	}

	return &mcptypes.ConfigValidateOutput{
		Valid: true,
	}
}

// ValidateRuntimeDescription validates a RuntimeDescription and returns validation results.
// It checks required fields and validates enum values.
func ValidateRuntimeDescription(s *RuntimeDescription) *mcptypes.ConfigValidateOutput {
	if s == nil {
		return &mcptypes.ConfigValidateOutput{
			Valid: true,
		}
	}

	var errors []mcptypes.ValidationError
	// Validate required array of references: artifacts
	if len(s.Artifacts) == 0 {
		errors = append(errors, mcptypes.ValidationError{
			Field:   "spec.artifacts",
			Message: "required field is missing or empty",
		})
	}
	// Validate array of references: artifacts
	for i, item := range s.Artifacts {
		nestedResult := ValidateRuntimeArtifact(&item)
		if !nestedResult.Valid {
			for _, e := range nestedResult.Errors {
				errors = append(errors, mcptypes.ValidationError{
					Field:   fmt.Sprintf("spec.artifacts[%d].%s", i, e.Field),
					Message: e.Message,
				})
			}
		}
	}
	// Validate array of references: prerequisites
	for i, item := range s.Prerequisites {
		nestedResult := ValidateRuntimePrerequisite(&item)
		if !nestedResult.Valid {
			for _, e := range nestedResult.Errors {
				errors = append(errors, mcptypes.ValidationError{
					Field:   fmt.Sprintf("spec.prerequisites[%d].%s", i, e.Field),
					Message: e.Message,
				})
			}
		}
	}
	// Validate required field: runtime
	if s.Runtime == "" {
		errors = append(errors, mcptypes.ValidationError{
			Field:   "spec.runtime",
			Message: "required field is missing",
		})
	}
	// Validate required field: version
	if s.Version == "" {
		errors = append(errors, mcptypes.ValidationError{
			Field:   "spec.version",
			Message: "required field is missing",
		})
	}

	if len(errors) > 0 {
		return &mcptypes.ConfigValidateOutput{
			Valid:  false,
			Errors: errors,
		}
	}

	return &mcptypes.ConfigValidateOutput{
		Valid: true,
	}
}

// ValidateInstallInput validates a InstallInput and returns validation results.
// It checks required fields and validates enum values.
func ValidateInstallInput(s *InstallInput) *mcptypes.ConfigValidateOutput {
	if s == nil {
		return &mcptypes.ConfigValidateOutput{
			Valid: true,
		}
	}

	var errors []mcptypes.ValidationError
	// Validate required array of references: archives
	if len(s.Archives) == 0 {
		errors = append(errors, mcptypes.ValidationError{
			Field:   "spec.archives",
			Message: "required field is missing or empty",
		})
	}
	// Validate array of references: archives
	for i, item := range s.Archives {
		nestedResult := ValidateFetchedArchive(&item)
		if !nestedResult.Valid {
			for _, e := range nestedResult.Errors {
				errors = append(errors, mcptypes.ValidationError{
					Field:   fmt.Sprintf("spec.archives[%d].%s", i, e.Field),
					Message: e.Message,
				})
			}
		}
	}
	// Validate required field: prefix
	if s.Prefix == "" {
		errors = append(errors, mcptypes.ValidationError{
			Field:   "spec.prefix",
			Message: "required field is missing",
		})
	}
	// Validate nested reference: spec
	{
		nested := s.Spec
		nestedResult := ValidateSpec(&nested)
		if !nestedResult.Valid {
			for _, e := range nestedResult.Errors {
				errors = append(errors, mcptypes.ValidationError{
					Field:   "spec.spec." + e.Field,
					Message: e.Message,
				})
			}
		}
	}

	if len(errors) > 0 {
		return &mcptypes.ConfigValidateOutput{
			Valid:  false,
			Errors: errors,
		}
	}

	return &mcptypes.ConfigValidateOutput{
		Valid: true,
	}
}

// Validate validates a Spec and returns validation results.
// This is the main entry point for validation.
func Validate(s *Spec) *mcptypes.ConfigValidateOutput {
	return ValidateSpec(s)
}

// ValidateMap validates a map[string]interface{} by first parsing it to a Spec.
// This is a convenience function for validating spec data from forge.yaml.
func ValidateMap(m map[string]interface{}) *mcptypes.ConfigValidateOutput {
	s, err := FromMap(m)
	if err != nil {
		return &mcptypes.ConfigValidateOutput{
			Valid: false,
			Errors: []mcptypes.ValidationError{
				{
					Field:   "spec",
					Message: err.Error(),
				},
			},
		}
	}

	return Validate(s)
}
