// Code generated by forge-dev. DO NOT EDIT.
// Source: spec.openapi.yaml
// SourceChecksum: sha256:8c3473067a76a1acb639f7089c6f241339387b7848dc816918f49ebbe03c1953

package main

import (
	"context"
	"fmt"

	"github.com/alexandremahdhaoui/forge/pkg/mcpserver"
	"github.com/alexandremahdhaoui/forge/pkg/mcptypes"
	"github.com/alexandremahdhaoui/forge/pkg/mcputil"
	"github.com/modelcontextprotocol/go-sdk/mcp"
)

// FetchFunc is the handler signature for the fetch tool.
// Bring one artifact's bytes to a local path, hash-verified. The spec's rewrite rules retarget url prefixes at a mirror or an internal artifact store.
type FetchFunc func(
	ctx context.Context,
	input FetchInput,
) (*FetchOutput, error)

// Handlers holds one implementation per tool declared in forge-dev.yaml.
// Every field is required. A nil field makes SetupMCPServer return an error
// rather than registering a tool that panics when called.
type Handlers struct {
	// Fetch implements the fetch tool.
	Fetch FetchFunc
}

// SetupMCPServer creates the MCP server and registers every declared tool plus
// config-validate.
func SetupMCPServer(name string, version string, handlers Handlers) (*mcpserver.Server, error) {
	server := mcpserver.New(name, version)

	if handlers.Fetch == nil {
		return nil, fmt.Errorf("Handlers.Fetch is required for the %q tool", "fetch")
	}

	mcpserver.RegisterTool(server, &mcp.Tool{
		Name:        "fetch",
		Description: "Bring one artifact's bytes to a local path, hash-verified. The spec's rewrite rules retarget url prefixes at a mirror or an internal artifact store.",
	}, wrapFetch(handlers.Fetch))

	mcpserver.RegisterTool(server, &mcp.Tool{
		Name:        "config-validate",
		Description: fmt.Sprintf("Validate %s engine-specific spec configuration.", name),
	}, handleConfigValidate)

	return server, nil
}

// wrapFetch adapts FetchFunc to the MCP tool handler shape.
func wrapFetch(fn FetchFunc) func(
	context.Context, *mcp.CallToolRequest, FetchInput,
) (*mcp.CallToolResult, any, error) {
	return func(
		ctx context.Context,
		_ *mcp.CallToolRequest,
		input FetchInput,
	) (*mcp.CallToolResult, any, error) {
		output, err := fn(ctx, input)
		if err != nil {
			return nil, nil, err
		}

		return nil, output, nil
	}
}

// handleConfigValidate handles the config-validate MCP tool.
func handleConfigValidate(
	_ context.Context,
	_ *mcp.CallToolRequest,
	input mcptypes.ConfigValidateInput,
) (*mcp.CallToolResult, any, error) {
	output := ValidateMap(input.Spec)

	if output.Valid {
		result, artifact := mcputil.SuccessResultWithArtifact("Configuration is valid", output)

		return result, artifact, nil
	}

	result, artifact := mcputil.SuccessResultWithArtifact(
		fmt.Sprintf("Configuration validation failed with %d error(s)", len(output.Errors)),
		output,
	)

	return result, artifact, nil
}
