// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package toolingcontrollermock

import (
	"context"

	"github.com/alexandremahdhaoui/forge-factory/internal/controller/toolingcontroller"
	mock "github.com/stretchr/testify/mock"
)

// NewMockApplier creates a new instance of MockApplier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockApplier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockApplier {
	mock := &MockApplier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockApplier is an autogenerated mock type for the Applier type
type MockApplier struct {
	mock.Mock
}

type MockApplier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockApplier) EXPECT() *MockApplier_Expecter {
	return &MockApplier_Expecter{mock: &_m.Mock}
}

// Apply provides a mock function for the type MockApplier
func (_mock *MockApplier) Apply(req toolingcontroller.Request) (toolingcontroller.Report, error) {
	ret := _mock.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for Apply")
	}

	var r0 toolingcontroller.Report
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(toolingcontroller.Request) (toolingcontroller.Report, error)); ok {
		return returnFunc(req)
	}
	if returnFunc, ok := ret.Get(0).(func(toolingcontroller.Request) toolingcontroller.Report); ok {
		r0 = returnFunc(req)
	} else {
		r0 = ret.Get(0).(toolingcontroller.Report)
	}
	if returnFunc, ok := ret.Get(1).(func(toolingcontroller.Request) error); ok {
		r1 = returnFunc(req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockApplier_Apply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Apply'
type MockApplier_Apply_Call struct {
	*mock.Call
}

// Apply is a helper method to define mock.On call
//   - req toolingcontroller.Request
func (_e *MockApplier_Expecter) Apply(req any) *MockApplier_Apply_Call {
	return &MockApplier_Apply_Call{Call: _e.mock.On("Apply", req)}
}

func (_c *MockApplier_Apply_Call) Run(run func(req toolingcontroller.Request)) *MockApplier_Apply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 toolingcontroller.Request
		if args[0] != nil {
			arg0 = args[0].(toolingcontroller.Request)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockApplier_Apply_Call) Return(report toolingcontroller.Report, err error) *MockApplier_Apply_Call {
	_c.Call.Return(report, err)
	return _c
}

func (_c *MockApplier_Apply_Call) RunAndReturn(run func(req toolingcontroller.Request) (toolingcontroller.Report, error)) *MockApplier_Apply_Call {
	_c.Call.Return(run)
	return _c
}

// ProvisionBinaries provides a mock function for the type MockApplier
func (_mock *MockApplier) ProvisionBinaries(ctx context.Context, root string, storeDir string, binaries []toolingcontroller.Binary) (toolingcontroller.BinaryReport, error) {
	ret := _mock.Called(ctx, root, storeDir, binaries)

	if len(ret) == 0 {
		panic("no return value specified for ProvisionBinaries")
	}

	var r0 toolingcontroller.BinaryReport
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []toolingcontroller.Binary) (toolingcontroller.BinaryReport, error)); ok {
		return returnFunc(ctx, root, storeDir, binaries)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []toolingcontroller.Binary) toolingcontroller.BinaryReport); ok {
		r0 = returnFunc(ctx, root, storeDir, binaries)
	} else {
		r0 = ret.Get(0).(toolingcontroller.BinaryReport)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, []toolingcontroller.Binary) error); ok {
		r1 = returnFunc(ctx, root, storeDir, binaries)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockApplier_ProvisionBinaries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProvisionBinaries'
type MockApplier_ProvisionBinaries_Call struct {
	*mock.Call
}

// ProvisionBinaries is a helper method to define mock.On call
//   - ctx context.Context
//   - root string
//   - storeDir string
//   - binaries []toolingcontroller.Binary
func (_e *MockApplier_Expecter) ProvisionBinaries(ctx any, root any, storeDir any, binaries any) *MockApplier_ProvisionBinaries_Call {
	return &MockApplier_ProvisionBinaries_Call{Call: _e.mock.On("ProvisionBinaries", ctx, root, storeDir, binaries)}
}

func (_c *MockApplier_ProvisionBinaries_Call) Run(run func(ctx context.Context, root string, storeDir string, binaries []toolingcontroller.Binary)) *MockApplier_ProvisionBinaries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []toolingcontroller.Binary
		if args[3] != nil {
			arg3 = args[3].([]toolingcontroller.Binary)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockApplier_ProvisionBinaries_Call) Return(binaryReport toolingcontroller.BinaryReport, err error) *MockApplier_ProvisionBinaries_Call {
	_c.Call.Return(binaryReport, err)
	return _c
}

func (_c *MockApplier_ProvisionBinaries_Call) RunAndReturn(run func(ctx context.Context, root string, storeDir string, binaries []toolingcontroller.Binary) (toolingcontroller.BinaryReport, error)) *MockApplier_ProvisionBinaries_Call {
	_c.Call.Return(run)
	return _c
}
