// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package toolingcontrollermock

import (
	"github.com/alexandremahdhaoui/forge-factory/internal/controller/toolingcontroller"
	mock "github.com/stretchr/testify/mock"
)

// NewMockApplier creates a new instance of MockApplier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockApplier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockApplier {
	mock := &MockApplier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockApplier is an autogenerated mock type for the Applier type
type MockApplier struct {
	mock.Mock
}

type MockApplier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockApplier) EXPECT() *MockApplier_Expecter {
	return &MockApplier_Expecter{mock: &_m.Mock}
}

// Apply provides a mock function for the type MockApplier
func (_mock *MockApplier) Apply(req toolingcontroller.Request) (toolingcontroller.Report, error) {
	ret := _mock.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for Apply")
	}

	var r0 toolingcontroller.Report
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(toolingcontroller.Request) (toolingcontroller.Report, error)); ok {
		return returnFunc(req)
	}
	if returnFunc, ok := ret.Get(0).(func(toolingcontroller.Request) toolingcontroller.Report); ok {
		r0 = returnFunc(req)
	} else {
		r0 = ret.Get(0).(toolingcontroller.Report)
	}
	if returnFunc, ok := ret.Get(1).(func(toolingcontroller.Request) error); ok {
		r1 = returnFunc(req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockApplier_Apply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Apply'
type MockApplier_Apply_Call struct {
	*mock.Call
}

// Apply is a helper method to define mock.On call
//   - req toolingcontroller.Request
func (_e *MockApplier_Expecter) Apply(req any) *MockApplier_Apply_Call {
	return &MockApplier_Apply_Call{Call: _e.mock.On("Apply", req)}
}

func (_c *MockApplier_Apply_Call) Run(run func(req toolingcontroller.Request)) *MockApplier_Apply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 toolingcontroller.Request
		if args[0] != nil {
			arg0 = args[0].(toolingcontroller.Request)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockApplier_Apply_Call) Return(report toolingcontroller.Report, err error) *MockApplier_Apply_Call {
	_c.Call.Return(report, err)
	return _c
}

func (_c *MockApplier_Apply_Call) RunAndReturn(run func(req toolingcontroller.Request) (toolingcontroller.Report, error)) *MockApplier_Apply_Call {
	_c.Call.Return(run)
	return _c
}
