// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package runcontrollermock

import (
	"context"

	"github.com/alexandremahdhaoui/forge-factory/internal/controller/runcontroller"
	"github.com/alexandremahdhaoui/forge-factory/pkg/config"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRunner creates a new instance of MockRunner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRunner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRunner {
	mock := &MockRunner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRunner is an autogenerated mock type for the Runner type
type MockRunner struct {
	mock.Mock
}

type MockRunner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRunner) EXPECT() *MockRunner_Expecter {
	return &MockRunner_Expecter{mock: &_m.Mock}
}

// Bootstrap provides a mock function for the type MockRunner
func (_mock *MockRunner) Bootstrap(ctx context.Context, req runcontroller.BootstrapRequest) (config.Factory, string, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Bootstrap")
	}

	var r0 config.Factory
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, runcontroller.BootstrapRequest) (config.Factory, string, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, runcontroller.BootstrapRequest) config.Factory); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Get(0).(config.Factory)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, runcontroller.BootstrapRequest) string); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, runcontroller.BootstrapRequest) error); ok {
		r2 = returnFunc(ctx, req)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockRunner_Bootstrap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Bootstrap'
type MockRunner_Bootstrap_Call struct {
	*mock.Call
}

// Bootstrap is a helper method to define mock.On call
//   - ctx context.Context
//   - req runcontroller.BootstrapRequest
func (_e *MockRunner_Expecter) Bootstrap(ctx any, req any) *MockRunner_Bootstrap_Call {
	return &MockRunner_Bootstrap_Call{Call: _e.mock.On("Bootstrap", ctx, req)}
}

func (_c *MockRunner_Bootstrap_Call) Run(run func(ctx context.Context, req runcontroller.BootstrapRequest)) *MockRunner_Bootstrap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 runcontroller.BootstrapRequest
		if args[1] != nil {
			arg1 = args[1].(runcontroller.BootstrapRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRunner_Bootstrap_Call) Return(factory config.Factory, s string, err error) *MockRunner_Bootstrap_Call {
	_c.Call.Return(factory, s, err)
	return _c
}

func (_c *MockRunner_Bootstrap_Call) RunAndReturn(run func(ctx context.Context, req runcontroller.BootstrapRequest) (config.Factory, string, error)) *MockRunner_Bootstrap_Call {
	_c.Call.Return(run)
	return _c
}

// Run provides a mock function for the type MockRunner
func (_mock *MockRunner) Run(ctx context.Context, req runcontroller.Request) (int, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, runcontroller.Request) (int, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, runcontroller.Request) int); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, runcontroller.Request) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRunner_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockRunner_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
//   - req runcontroller.Request
func (_e *MockRunner_Expecter) Run(ctx any, req any) *MockRunner_Run_Call {
	return &MockRunner_Run_Call{Call: _e.mock.On("Run", ctx, req)}
}

func (_c *MockRunner_Run_Call) Run(run func(ctx context.Context, req runcontroller.Request)) *MockRunner_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 runcontroller.Request
		if args[1] != nil {
			arg1 = args[1].(runcontroller.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRunner_Run_Call) Return(n int, err error) *MockRunner_Run_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockRunner_Run_Call) RunAndReturn(run func(ctx context.Context, req runcontroller.Request) (int, error)) *MockRunner_Run_Call {
	_c.Call.Return(run)
	return _c
}
