// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package runtimecontrollermock

import (
	"context"

	"github.com/alexandremahdhaoui/forge-factory/internal/controller/runtimecontroller"
	"github.com/alexandremahdhaoui/forge-factory/pkg/config"
	mock "github.com/stretchr/testify/mock"
)

// NewMockProvisioner creates a new instance of MockProvisioner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProvisioner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProvisioner {
	mock := &MockProvisioner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProvisioner is an autogenerated mock type for the Provisioner type
type MockProvisioner struct {
	mock.Mock
}

type MockProvisioner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProvisioner) EXPECT() *MockProvisioner_Expecter {
	return &MockProvisioner_Expecter{mock: &_m.Mock}
}

// Provision provides a mock function for the type MockProvisioner
func (_mock *MockProvisioner) Provision(ctx context.Context, f config.Factory, root string, storeDir string, pins []runtimecontroller.Pin) (runtimecontroller.Report, error) {
	ret := _mock.Called(ctx, f, root, storeDir, pins)

	if len(ret) == 0 {
		panic("no return value specified for Provision")
	}

	var r0 runtimecontroller.Report
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, config.Factory, string, string, []runtimecontroller.Pin) (runtimecontroller.Report, error)); ok {
		return returnFunc(ctx, f, root, storeDir, pins)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, config.Factory, string, string, []runtimecontroller.Pin) runtimecontroller.Report); ok {
		r0 = returnFunc(ctx, f, root, storeDir, pins)
	} else {
		r0 = ret.Get(0).(runtimecontroller.Report)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, config.Factory, string, string, []runtimecontroller.Pin) error); ok {
		r1 = returnFunc(ctx, f, root, storeDir, pins)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProvisioner_Provision_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Provision'
type MockProvisioner_Provision_Call struct {
	*mock.Call
}

// Provision is a helper method to define mock.On call
//   - ctx context.Context
//   - f config.Factory
//   - root string
//   - storeDir string
//   - pins []runtimecontroller.Pin
func (_e *MockProvisioner_Expecter) Provision(ctx any, f any, root any, storeDir any, pins any) *MockProvisioner_Provision_Call {
	return &MockProvisioner_Provision_Call{Call: _e.mock.On("Provision", ctx, f, root, storeDir, pins)}
}

func (_c *MockProvisioner_Provision_Call) Run(run func(ctx context.Context, f config.Factory, root string, storeDir string, pins []runtimecontroller.Pin)) *MockProvisioner_Provision_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 config.Factory
		if args[1] != nil {
			arg1 = args[1].(config.Factory)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 []runtimecontroller.Pin
		if args[4] != nil {
			arg4 = args[4].([]runtimecontroller.Pin)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockProvisioner_Provision_Call) Return(report runtimecontroller.Report, err error) *MockProvisioner_Provision_Call {
	_c.Call.Return(report, err)
	return _c
}

func (_c *MockProvisioner_Provision_Call) RunAndReturn(run func(ctx context.Context, f config.Factory, root string, storeDir string, pins []runtimecontroller.Pin) (runtimecontroller.Report, error)) *MockProvisioner_Provision_Call {
	_c.Call.Return(run)
	return _c
}
