// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package execadaptermock

import (
	"context"

	"github.com/alexandremahdhaoui/forge-factory/internal/adapter/execadapter"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRunner creates a new instance of MockRunner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRunner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRunner {
	mock := &MockRunner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRunner is an autogenerated mock type for the Runner type
type MockRunner struct {
	mock.Mock
}

type MockRunner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRunner) EXPECT() *MockRunner_Expecter {
	return &MockRunner_Expecter{mock: &_m.Mock}
}

// LookPath provides a mock function for the type MockRunner
func (_mock *MockRunner) LookPath(name string) (string, bool) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for LookPath")
	}

	var r0 string
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(string) (string, bool)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(name)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) bool); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockRunner_LookPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LookPath'
type MockRunner_LookPath_Call struct {
	*mock.Call
}

// LookPath is a helper method to define mock.On call
//   - name string
func (_e *MockRunner_Expecter) LookPath(name any) *MockRunner_LookPath_Call {
	return &MockRunner_LookPath_Call{Call: _e.mock.On("LookPath", name)}
}

func (_c *MockRunner_LookPath_Call) Run(run func(name string)) *MockRunner_LookPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRunner_LookPath_Call) Return(s string, b bool) *MockRunner_LookPath_Call {
	_c.Call.Return(s, b)
	return _c
}

func (_c *MockRunner_LookPath_Call) RunAndReturn(run func(name string) (string, bool)) *MockRunner_LookPath_Call {
	_c.Call.Return(run)
	return _c
}

// Run provides a mock function for the type MockRunner
func (_mock *MockRunner) Run(ctx context.Context, dir string, name string, args ...string) (execadapter.Result, error) {
	// string
	_va := make([]any, len(args))
	for _i := range args {
		_va[_i] = args[_i]
	}
	var _ca []any
	_ca = append(_ca, ctx, dir, name)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 execadapter.Result
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, ...string) (execadapter.Result, error)); ok {
		return returnFunc(ctx, dir, name, args...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, ...string) execadapter.Result); ok {
		r0 = returnFunc(ctx, dir, name, args...)
	} else {
		r0 = ret.Get(0).(execadapter.Result)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, ...string) error); ok {
		r1 = returnFunc(ctx, dir, name, args...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRunner_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockRunner_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
//   - dir string
//   - name string
//   - args ...string
func (_e *MockRunner_Expecter) Run(ctx any, dir any, name any, args ...any) *MockRunner_Run_Call {
	return &MockRunner_Run_Call{Call: _e.mock.On("Run",
		append([]any{ctx, dir, name}, args...)...)}
}

func (_c *MockRunner_Run_Call) Run(run func(ctx context.Context, dir string, name string, args ...string)) *MockRunner_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []string
		variadicArgs := make([]string, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockRunner_Run_Call) Return(result execadapter.Result, err error) *MockRunner_Run_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *MockRunner_Run_Call) RunAndReturn(run func(ctx context.Context, dir string, name string, args ...string) (execadapter.Result, error)) *MockRunner_Run_Call {
	_c.Call.Return(run)
	return _c
}

// RunAttached provides a mock function for the type MockRunner
func (_mock *MockRunner) RunAttached(ctx context.Context, dir string, env map[string]string, name string, args ...string) (int, error) {
	// string
	_va := make([]any, len(args))
	for _i := range args {
		_va[_i] = args[_i]
	}
	var _ca []any
	_ca = append(_ca, ctx, dir, env, name)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for RunAttached")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, map[string]string, string, ...string) (int, error)); ok {
		return returnFunc(ctx, dir, env, name, args...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, map[string]string, string, ...string) int); ok {
		r0 = returnFunc(ctx, dir, env, name, args...)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, map[string]string, string, ...string) error); ok {
		r1 = returnFunc(ctx, dir, env, name, args...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRunner_RunAttached_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunAttached'
type MockRunner_RunAttached_Call struct {
	*mock.Call
}

// RunAttached is a helper method to define mock.On call
//   - ctx context.Context
//   - dir string
//   - env map[string]string
//   - name string
//   - args ...string
func (_e *MockRunner_Expecter) RunAttached(ctx any, dir any, env any, name any, args ...any) *MockRunner_RunAttached_Call {
	return &MockRunner_RunAttached_Call{Call: _e.mock.On("RunAttached",
		append([]any{ctx, dir, env, name}, args...)...)}
}

func (_c *MockRunner_RunAttached_Call) Run(run func(ctx context.Context, dir string, env map[string]string, name string, args ...string)) *MockRunner_RunAttached_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 map[string]string
		if args[2] != nil {
			arg2 = args[2].(map[string]string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 []string
		variadicArgs := make([]string, len(args)-4)
		for i, a := range args[4:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		arg4 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4...,
		)
	})
	return _c
}

func (_c *MockRunner_RunAttached_Call) Return(n int, err error) *MockRunner_RunAttached_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockRunner_RunAttached_Call) RunAndReturn(run func(ctx context.Context, dir string, env map[string]string, name string, args ...string) (int, error)) *MockRunner_RunAttached_Call {
	_c.Call.Return(run)
	return _c
}

// RunEnv provides a mock function for the type MockRunner
func (_mock *MockRunner) RunEnv(ctx context.Context, dir string, env map[string]string, name string, args ...string) (execadapter.Result, error) {
	// string
	_va := make([]any, len(args))
	for _i := range args {
		_va[_i] = args[_i]
	}
	var _ca []any
	_ca = append(_ca, ctx, dir, env, name)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for RunEnv")
	}

	var r0 execadapter.Result
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, map[string]string, string, ...string) (execadapter.Result, error)); ok {
		return returnFunc(ctx, dir, env, name, args...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, map[string]string, string, ...string) execadapter.Result); ok {
		r0 = returnFunc(ctx, dir, env, name, args...)
	} else {
		r0 = ret.Get(0).(execadapter.Result)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, map[string]string, string, ...string) error); ok {
		r1 = returnFunc(ctx, dir, env, name, args...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRunner_RunEnv_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunEnv'
type MockRunner_RunEnv_Call struct {
	*mock.Call
}

// RunEnv is a helper method to define mock.On call
//   - ctx context.Context
//   - dir string
//   - env map[string]string
//   - name string
//   - args ...string
func (_e *MockRunner_Expecter) RunEnv(ctx any, dir any, env any, name any, args ...any) *MockRunner_RunEnv_Call {
	return &MockRunner_RunEnv_Call{Call: _e.mock.On("RunEnv",
		append([]any{ctx, dir, env, name}, args...)...)}
}

func (_c *MockRunner_RunEnv_Call) Run(run func(ctx context.Context, dir string, env map[string]string, name string, args ...string)) *MockRunner_RunEnv_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 map[string]string
		if args[2] != nil {
			arg2 = args[2].(map[string]string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 []string
		variadicArgs := make([]string, len(args)-4)
		for i, a := range args[4:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		arg4 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4...,
		)
	})
	return _c
}

func (_c *MockRunner_RunEnv_Call) Return(result execadapter.Result, err error) *MockRunner_RunEnv_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *MockRunner_RunEnv_Call) RunAndReturn(run func(ctx context.Context, dir string, env map[string]string, name string, args ...string) (execadapter.Result, error)) *MockRunner_RunEnv_Call {
	_c.Call.Return(run)
	return _c
}
